# Semiconductor Annual Report Research Pipeline

This notebook implements the final company-level pipeline for a semiconductor supply-chain
thesis project. It is designed to process annual report PDFs, retrieve relevant passages,
classify them with a controlled coding scheme, and export one Excel workbook per company.

Main design choices in this final version:

- the notebook supports both a `single_company` test workflow and a `full_corpus` workflow
- each company is processed independently from discovery through export
- final outputs are uncapped: the notebook does not suppress relevant passages above a target
- retrieval is broadened to improve recall
- page and chunk quality are filtered before retrieval
- `strategy_category` is normalized to a controlled set of E1-E7 labels or `I-*`
- the original passage text is never rewritten by the LLM

The notebook is heavily commented so that each step is understandable and easy to adapt.

## 1. Project Overview

The final pipeline runs in this order:

1. Discover all PDFs recursively under the base folder.
2. Parse company names and fiscal years from folder and filename patterns.
3. Filter the file set based on the selected run mode.
4. Extract page-level text from each report.
5. Remove repeated headers and footers and exclude noisy navigation pages.
6. Chunk only the clean pages into research-friendly passages.
7. Build or reuse a per-company vector index.
8. Run a broader retrieval query pack inside each company corpus.
9. Deduplicate retrieved chunks before classification.
10. Classify each retrieved chunk with a controlled output schema.
11. Normalize labels and filter irrelevant chunks.
12. Export one Excel workbook per company plus optional combined QA outputs.

Important principle:
The `passage` field always contains the original chunk text from the annual report.
The model is used only for classification, not rewriting.

## 2. Imports and Setup

Install missing dependencies in your local environment before running the notebook.
Typical installs:

```bash
pip install pandas openpyxl pymupdf sentence-transformers faiss-cpu tqdm openai
```

If you prefer a different PDF parser, vector store, or model provider later, the notebook is
organized so those components can be swapped in helper functions instead of rewriting the whole
workflow.

In [20]:
from __future__ import annotations

import json
import logging
import os
import pickle
import re
import textwrap
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from collections import Counter
from dataclasses import asdict, dataclass
from hashlib import sha1
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import faiss
import fitz  # PyMuPDF
import numpy as np
import pandas as pd
from pandas.api.types import is_string_dtype
from IPython.display import display
from openai import OpenAI
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm

from pathlib import Path
from dotenv import load_dotenv
load_dotenv(override=True)
load_dotenv(Path("/Users/paulkoslowsky/Github/Jakop") / ".env")


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("semiconductor_pipeline")


pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)
pd.set_option("display.max_colwidth", 180)

## 3. Configuration

Edit this section first when you want to change how the notebook runs.

The two main modes are:

- `single_company`: recommended for testing the full workflow on one firm across all years
- `full_corpus`: run the same workflow for every company discovered in the corpus

This final notebook writes company-level outputs by default and keeps a combined master table
only for QA and optional cross-company analysis.

In [21]:
CONFIG: Dict[str, Any] = {
    # Main run control
    "run_mode": "full_corpus",  # Options: "single_company", "full_corpus"
    "selected_company": None,
    "selected_years": None,  # Example: [2024, 2025]
    "max_files": None,  # Optional quick debugging limit
    # Input and output paths
    "base_input_folder": Path("Data"),
    "output_root": Path("outputs/final_pipeline"),
    "company_export_folder": Path("outputs/final_pipeline/company_excels"),
    "combined_export_folder": Path("outputs/final_pipeline/combined"),
    "intermediate_root": Path("outputs/final_pipeline/intermediate"),
    "vector_store_root": Path("outputs/final_pipeline/vector_store"),
    # Caching and reruns
    "rebuild_index": False,
    "use_cached_pages": True,
    "use_cached_chunks": True,
    "use_cached_retrieval": True,
    "use_cached_classification": True,
    # Chunking controls
    "chunk_size_chars": 1800,
    "chunk_overlap_chars": 250,
    "min_chunk_chars": 280,
    # Retrieval controls
    "top_k_retrieval": 25,
    "embedding_batch_size": 32,
    # Output behavior
    "write_company_excels": True,
    "export_combined_master": True,
    "low_output_warning_threshold": 50,
    # Quality filters
    "drop_table_of_contents_pages": False,
    "strip_repeated_headers_footers": True,
    "filter_low_quality_chunks": True,
    # Model settings
    "embedding_model_name": "sentence-transformers/all-MiniLM-L6-v2",
    "openai_model_name": "gpt-5.4-mini",
    "openai_api_key_env_var": "OPENAI_API_KEY",
    "classification_max_workers": 40,
    "run_classification": True,
}


COMPANY_SCOPE_RULES: Dict[str, Dict[str, str]] = {
    "Samsung": {
        "retrieval_scope_suffix": (
            "Focus only on Samsung DS division semiconductor memory foundry and firm-level "
            "statements that clearly apply to those businesses."
        ),
        "classification_scope": (
            "For Samsung, only keep passages relevant to the DS Division, semiconductor, memory, "
            "or foundry context. Exclude other business units unless the passage clearly refers to "
            "the whole company and is materially relevant to semiconductor supply-chain strategy."
        ),
    },
    "MediaTek": {
        "retrieval_scope_suffix": (
            "Focus only on MediaTek Inc. core semiconductor business and exclude unrelated "
            "subsidiary contexts."
        ),
        "classification_scope": (
            "For MediaTek, only keep passages about MediaTek Inc. itself and its semiconductor "
            "business. Exclude unrelated subsidiary content that does not materially concern the "
            "semiconductor industry."
        ),
    },
}


# Create the main output folders up front.
for output_path in [
    CONFIG["output_root"],
    CONFIG["company_export_folder"],
    CONFIG["combined_export_folder"],
    CONFIG["intermediate_root"],
    CONFIG["vector_store_root"],
]:
    output_path.mkdir(parents=True, exist_ok=True)


print("Active configuration:")
for key, value in CONFIG.items():
    print(f"- {key}: {value}")

Active configuration:
- run_mode: full_corpus
- selected_company: None
- selected_years: None
- max_files: None
- base_input_folder: Data
- output_root: outputs/final_pipeline
- company_export_folder: outputs/final_pipeline/company_excels
- combined_export_folder: outputs/final_pipeline/combined
- intermediate_root: outputs/final_pipeline/intermediate
- vector_store_root: outputs/final_pipeline/vector_store
- rebuild_index: False
- use_cached_pages: True
- use_cached_chunks: True
- use_cached_retrieval: True
- use_cached_classification: True
- chunk_size_chars: 1800
- chunk_overlap_chars: 250
- min_chunk_chars: 280
- top_k_retrieval: 25
- embedding_batch_size: 32
- write_company_excels: True
- export_combined_master: True
- low_output_warning_threshold: 50
- drop_table_of_contents_pages: False
- strip_repeated_headers_footers: True
- filter_low_quality_chunks: True
- embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
- openai_model_name: gpt-5.4-mini
- openai_api_key_env_var: OPENAI_API_KEY
- classification_max_workers: 40
- run_classification: True

## 4. Controlled Taxonomy and Retrieval Query Pack

This section defines:

- the controlled `strategy_category` values used in the final export
- the broader retrieval query pack used to improve recall

The LLM is asked to classify into the controlled taxonomy. In the tightened final coding
scheme, `secondary_category` is limited to `0` or the same E1-E7 framework, and `orientation`
is limited to `proactive`, `reactive`, or `descriptive`.

In [22]:
CONTROLLED_STRATEGY_CATEGORIES: List[str] = [
    "E1 Operational Buffers",
    "E2 Footprint Diversification",
    "E3 Supply Option Diversification",
    "E4 Robust Distribution",
    "E5 Product Standardisation",
    "E6 Partner Network Strengthening",
    "E7 SCRM and Visibility",
]

ALLOWED_ORIENTATION_VALUES: List[str] = [
    "proactive",
    "reactive",
    "descriptive",
]

PREFERRED_INDUCTIVE_CODES: List[str] = [
    "I-GovernmentSubsidy",
    "I-ExportControlCompliance",
    "I-MaterialStockpiling",
]

ALLOWED_GEOPOLITICAL_TRIGGERS: List[str] = [
    "COVID-19 pandemic",
    "Russia-Ukraine war",
    "U.S.-China trade tensions",
    "U.S. export controls on China",
    "CHIPS Act and public subsidy programs",
    "Taiwan Strait tensions",
    "Sanctions or entity-list restrictions",
    "Critical-material or energy supply disruption",
]


THEME_TO_CONTROLLED_CATEGORY: Dict[str, str] = {
    "E1 Operational Buffers": "E1 Operational Buffers",
    "E2 Footprint Diversification": "E2 Footprint Diversification",
    "E3 Supply Option Diversification": "E3 Supply Option Diversification",
    "E4 Robust Distribution": "E4 Robust Distribution",
    "E5 Product Standardisation": "E5 Product Standardisation",
    "E6 Partner Network Strengthening": "E6 Partner Network Strengthening",
    "E7 SCRM and Visibility": "E7 SCRM and Visibility",
    "Broad geopolitical context": "E7 SCRM and Visibility",
}


QUERY_PACK: List[Dict[str, str]] = [
    {
        "retrieval_theme": "E1 Operational Buffers",
        "retrieval_query": "E1 broad",
        "query_text": "semiconductor safety stock inventory buffer capacity shortage supply disruption resilience",
    },
    {
        "retrieval_theme": "E1 Operational Buffers",
        "retrieval_query": "E1 capacity hedge",
        "query_text": "semiconductor capacity buffer substrate inventory build contingency buffer demand volatility",
    },
    {
        "retrieval_theme": "E1 Operational Buffers",
        "retrieval_query": "E1 annual report phrasing",
        "query_text": "annual report semiconductor maintain inventory levels increase buffer stock capacity constraints bottlenecks",
    },
    {
        "retrieval_theme": "E2 Footprint Diversification",
        "retrieval_query": "E2 broad",
        "query_text": "semiconductor manufacturing footprint diversification geographic expansion new fab region nearshoring",
    },
    {
        "retrieval_theme": "E2 Footprint Diversification",
        "retrieval_query": "E2 foundry footprint",
        "query_text": "semiconductor fab location capacity expansion site selection region manufacturing network",
    },
    {
        "retrieval_theme": "E2 Footprint Diversification",
        "retrieval_query": "E2 annual report phrasing",
        "query_text": "annual report semiconductor geographically balanced supply chain manufacturing footprint expansion external foundry region",
    },
    {
        "retrieval_theme": "E3 Supply Option Diversification",
        "retrieval_query": "E3 broad",
        "query_text": "semiconductor dual sourcing alternative supplier second source backup supply substrate wafer materials",
    },
    {
        "retrieval_theme": "E3 Supply Option Diversification",
        "retrieval_query": "E3 supplier resilience",
        "query_text": "semiconductor supplier diversification alternate suppliers procurement sourcing redundancy qualified suppliers",
    },
    {
        "retrieval_theme": "E3 Supply Option Diversification",
        "retrieval_query": "E3 annual report phrasing",
        "query_text": "annual report semiconductor qualify alternate suppliers diversify sourcing reduce supplier dependency",
    },
    {
        "retrieval_theme": "E4 Robust Distribution",
        "retrieval_query": "E4 broad",
        "query_text": "semiconductor logistics resilience distribution network freight transportation disruption flexibility channel management",
    },
    {
        "retrieval_theme": "E4 Robust Distribution",
        "retrieval_query": "E4 shipment continuity",
        "query_text": "semiconductor shipment delays freight constraints distribution continuity customer delivery resilience",
    },
    {
        "retrieval_theme": "E4 Robust Distribution",
        "retrieval_query": "E4 annual report phrasing",
        "query_text": "annual report semiconductor logistics distribution channel freight transport disruption risk flexibility",
    },
    {
        "retrieval_theme": "E5 Product Standardisation",
        "retrieval_query": "E5 broad",
        "query_text": "semiconductor product standardisation platform architecture common design SKU rationalisation complexity reduction",
    },
    {
        "retrieval_theme": "E5 Product Standardisation",
        "retrieval_query": "E5 modular design",
        "query_text": "semiconductor platform reuse modular design common components product simplification supply chain complexity",
    },
    {
        "retrieval_theme": "E5 Product Standardisation",
        "retrieval_query": "E5 annual report phrasing",
        "query_text": "annual report semiconductor common platform architecture standardize product portfolio reduce complexity",
    },
    {
        "retrieval_theme": "E6 Partner Network Strengthening",
        "retrieval_query": "E6 broad",
        "query_text": "semiconductor long term supply agreement capacity reservation partnership collaboration foundry customer agreement",
    },
    {
        "retrieval_theme": "E6 Partner Network Strengthening",
        "retrieval_query": "E6 ecosystem",
        "query_text": "semiconductor strategic partnership supplier collaboration customer collaboration foundry ecosystem secure capacity",
    },
    {
        "retrieval_theme": "E6 Partner Network Strengthening",
        "retrieval_query": "E6 annual report phrasing",
        "query_text": "annual report semiconductor long-term agreements partnerships collaborations supply assurance capacity commitments",
    },
    {
        "retrieval_theme": "E7 SCRM and Visibility",
        "retrieval_query": "E7 broad",
        "query_text": "semiconductor supply chain risk management visibility supplier monitoring business continuity contingency planning risk assessment",
    },
    {
        "retrieval_theme": "E7 SCRM and Visibility",
        "retrieval_query": "E7 monitoring and control",
        "query_text": "semiconductor supplier monitoring early warning control tower business continuity contingency planning supply chain visibility",
    },
    {
        "retrieval_theme": "E7 SCRM and Visibility",
        "retrieval_query": "E7 annual report phrasing",
        "query_text": "annual report semiconductor risk management supplier monitoring continuity planning risk assessment supply chain visibility",
    },
    {
        "retrieval_theme": "Broad geopolitical context",
        "retrieval_query": "Broad geopolitical query",
        "query_text": "semiconductor export controls licensing entity list sanctions tariff compliance chips act government subsidies critical materials stockpiling",
    },
    {
        "retrieval_theme": "Broad geopolitical context",
        "retrieval_query": "Broad geopolitical manufacturing",
        "query_text": "semiconductor china export control manufacturing equipment restrictions localization regionalization decoupling subsidy compliance supply chain",
    },
]


EXPECTED_CLASSIFICATION_KEYS: List[str] = [
    "relevant",
    "strategy_category",
    "secondary_category",
    "geopolitical_trigger",
    "orientation",
    "main_point",
    "confidence",
]

## 5. Data Classes and Core Utilities

These data classes keep the main pipeline records explicit and readable.
The utility functions handle common tasks such as slug creation, persistence, and safe text
normalization.

In [23]:
@dataclass
class FileRecord:
    """Metadata for one discovered PDF file."""

    firm_name: Optional[str]
    fiscal_year: Optional[int]
    source_file: str
    folder_name: str
    file_name: str


@dataclass
class PageRecord:
    """Page-level record after extraction and cleaning."""

    firm_name: Optional[str]
    fiscal_year: Optional[int]
    source_file: str
    page_number: int
    section: Optional[str]
    page_text: str
    page_text_raw: str
    is_excluded: bool
    exclusion_reason: Optional[str]
    qa_flags: List[str]


@dataclass
class ChunkRecord:
    """Chunk-level record preserved through retrieval and export."""

    firm_name: Optional[str]
    fiscal_year: Optional[int]
    source_file: str
    page_number: int
    section: Optional[str]
    chunk_id: str
    passage: str
    qa_flags: List[str]
    is_excluded: bool
    exclusion_reason: Optional[str]


def save_pickle(obj: Any, path: Path) -> None:
    """Save a Python object to disk as a pickle file."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as file_handle:
        pickle.dump(obj, file_handle)


def load_pickle(path: Path) -> Any:
    """Load a pickle file from disk."""

    with path.open("rb") as file_handle:
        return pickle.load(file_handle)


def slugify(value: str) -> str:
    """Create a stable filesystem- and code-friendly slug."""

    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", value.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned.lower() or "unknown"


def normalise_whitespace(text: str) -> str:
    """Collapse messy whitespace while keeping paragraph breaks readable."""

    text = text.replace("\x00", " ")
    text = re.sub(r"\r\n?", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def normalize_for_matching(text: str) -> str:
    """Normalize a string for comparisons such as repeated line detection."""

    text = normalise_whitespace(text)
    text = re.sub(r"\s+", " ", text)
    return text.lower().strip()


def soft_normalize_passage(text: str) -> str:
    """Normalize a passage for conservative near-duplicate detection."""

    text = normalize_for_matching(text)
    text = re.sub(r"[^a-z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def alpha_ratio(text: str) -> float:
    """Return the share of alphabetic characters in a text."""

    if not text:
        return 0.0
    alpha_count = sum(character.isalpha() for character in text)
    return alpha_count / max(len(text), 1)


def build_company_output_paths(company_name: str) -> Dict[str, Path]:
    """Create the set of stable output paths used for one company."""

    company_slug = slugify(company_name)
    intermediate_dir = CONFIG["intermediate_root"] / company_slug
    vector_dir = CONFIG["vector_store_root"] / company_slug
    export_dir = CONFIG["company_export_folder"]

    intermediate_dir.mkdir(parents=True, exist_ok=True)
    vector_dir.mkdir(parents=True, exist_ok=True)
    export_dir.mkdir(parents=True, exist_ok=True)

    return {
        "company_slug": Path(company_slug),
        "intermediate_dir": intermediate_dir,
        "vector_dir": vector_dir,
        "manifest_path": intermediate_dir / "file_manifest.csv",
        "pages_path": intermediate_dir / "pdf_pages.pkl",
        "chunks_path": intermediate_dir / "chunks.pkl",
        "retrieval_path": intermediate_dir / "retrieved_chunks.pkl",
        "classification_path": intermediate_dir / "classified_chunks.pkl",
        "final_path": intermediate_dir / "final_relevant_chunks.pkl",
        "summary_path": intermediate_dir / "company_summary.csv",
        "faiss_index_path": vector_dir / "chunks.faiss",
        "faiss_metadata_path": vector_dir / "chunk_metadata.pkl",
        "company_excel_path": export_dir / f"{company_slug}_evidence.xlsx",
    }

## 6. File Discovery and Metadata Parsing

This section discovers all PDF files recursively and parses metadata from the folder/file
structure.

Important metadata rules:

- filename parsing is preferred over folder parsing
- folder parsing is used as a fallback
- year parsing is flexible but warnings are logged when a year cannot be found
- `single_company` mode filters to the chosen firm across all matching years

In [24]:
def extract_year_from_text(text: str) -> Optional[int]:
    """Extract the first plausible four-digit year from text."""

    match = re.search(r"(19|20)\d{2}", text)
    if not match:
        return None
    return int(match.group(0))


def clean_company_name(raw_name: str) -> str:
    """Normalize company names parsed from folder names or filenames."""

    cleaned = re.sub(r"[_\-]+", " ", raw_name)
    cleaned = re.sub(
        r"\b(annual|report|form 10 k|form 20 f|integrated|halfyear|half year|interim)\b",
        " ",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def parse_firm_and_year_from_path(pdf_path: Path) -> FileRecord:
    """Parse `firm_name` and `fiscal_year` from a PDF path."""

    folder_name = pdf_path.parent.name
    file_name = pdf_path.name
    stem = pdf_path.stem

    fiscal_year = extract_year_from_text(stem)
    if fiscal_year is None:
        fiscal_year = extract_year_from_text(folder_name)

    firm_name_from_filename = clean_company_name(re.sub(r"(19|20)\d{2}", " ", stem))
    firm_name_from_folder = clean_company_name(folder_name)
    firm_name = firm_name_from_filename or firm_name_from_folder or None

    if fiscal_year is None:
        logger.warning("Could not parse fiscal year for %s", pdf_path)

    return FileRecord(
        firm_name=firm_name,
        fiscal_year=fiscal_year,
        source_file=str(pdf_path.resolve()),
        folder_name=folder_name,
        file_name=file_name,
    )


def discover_pdf_files(
    base_folder: Path,
    selected_company: Optional[str] = None,
    selected_years: Optional[List[int]] = None,
    max_files: Optional[int] = None,
) -> pd.DataFrame:
    """Discover all PDF files recursively and return a manifest DataFrame."""

    records: List[FileRecord] = []

    for pdf_path in sorted(base_folder.rglob("*.pdf")):
        record = parse_firm_and_year_from_path(pdf_path)

        if selected_company and (record.firm_name or "").lower() != selected_company.lower():
            continue

        if selected_years and record.fiscal_year not in selected_years:
            continue

        records.append(record)

        if max_files is not None and len(records) >= max_files:
            break

    manifest_df = pd.DataFrame([asdict(record) for record in records])

    if manifest_df.empty:
        logger.warning("No PDF files found for the current selection.")
    else:
        logger.info(
            "Discovered %s PDFs across %s companies",
            len(manifest_df),
            manifest_df["firm_name"].nunique(dropna=True),
        )

    return manifest_df


def select_manifest_for_run(config: Dict[str, Any]) -> pd.DataFrame:
    """Select the manifest subset based on the configured run mode."""

    if config["run_mode"] == "single_company":
        return discover_pdf_files(
            base_folder=config["base_input_folder"],
            selected_company=config["selected_company"],
            selected_years=config["selected_years"],
            max_files=config["max_files"],
        )

    if config["run_mode"] == "full_corpus":
        return discover_pdf_files(
            base_folder=config["base_input_folder"],
            selected_company=None,
            selected_years=config["selected_years"],
            max_files=config["max_files"],
        )

    raise ValueError(f"Unsupported run_mode: {config['run_mode']}")

## 7. Page Extraction, Cleaning, and Page-Level QA

This section improves the earlier extraction logic in three ways:

- it strips repeated headers and footers at the report level
- it identifies probable table-of-contents or navigation pages before chunking
- it keeps page-level QA information so you can inspect what was excluded and why

The goal is to stop noisy content from entering the vector index in the first place.

In [25]:
def normalize_line_key(line: str) -> str:
    """Normalize a line for repeated header/footer detection."""

    line = normalize_for_matching(line)
    line = re.sub(r"\bpage\s+\d+\b", " ", line)
    line = re.sub(r"\b\d+\b", " ", line)
    line = re.sub(r"\s+", " ", line)
    return line.strip()


def is_repeated_line_candidate(line: str) -> bool:
    """Return True if a line is a plausible repeated header/footer candidate."""

    line = normalise_whitespace(line)
    if not line:
        return False
    if len(line) < 3 or len(line) > 120:
        return False
    if alpha_ratio(line) < 0.25:
        return False
    return True


def detect_repeated_edge_lines(page_line_bundles: List[List[str]]) -> set[str]:
    """Detect lines that repeat on many page edges within the same PDF."""

    edge_counter: Counter[str] = Counter()
    total_pages = len(page_line_bundles)
    min_hits = max(3, int(total_pages * 0.20))

    for page_lines in page_line_bundles:
        edge_lines = page_lines[:4] + page_lines[-4:]
        seen_keys = set()
        for line in edge_lines:
            if is_repeated_line_candidate(line):
                seen_keys.add(normalize_line_key(line))
        for line_key in seen_keys:
            edge_counter[line_key] += 1

    return {
        line_key
        for line_key, hit_count in edge_counter.items()
        if hit_count >= min_hits
    }


def clean_page_lines(
    raw_lines: List[str],
    repeated_edge_lines: set[str],
    strip_repeated_headers_footers: bool = True,
) -> List[str]:
    """Remove repeated headers/footers and trivial page-number lines from one page."""

    cleaned_lines = [normalise_whitespace(line) for line in raw_lines if normalise_whitespace(line)]
    page_number_pattern = re.compile(r"^(page\s+)?\d{1,4}$", flags=re.IGNORECASE)

    while cleaned_lines and page_number_pattern.match(cleaned_lines[0].strip()):
        cleaned_lines.pop(0)
    while cleaned_lines and page_number_pattern.match(cleaned_lines[-1].strip()):
        cleaned_lines.pop()

    if strip_repeated_headers_footers:
        lines_changed = True
        while cleaned_lines and lines_changed:
            lines_changed = False
            while cleaned_lines and normalize_line_key(cleaned_lines[0]) in repeated_edge_lines:
                cleaned_lines.pop(0)
                lines_changed = True
            while cleaned_lines and normalize_line_key(cleaned_lines[-1]) in repeated_edge_lines:
                cleaned_lines.pop()
                lines_changed = True
            while cleaned_lines and page_number_pattern.match(cleaned_lines[0].strip()):
                cleaned_lines.pop(0)
                lines_changed = True
            while cleaned_lines and page_number_pattern.match(cleaned_lines[-1].strip()):
                cleaned_lines.pop()
                lines_changed = True

    cleaned_lines = [line for line in cleaned_lines if not page_number_pattern.match(line.strip())]

    return cleaned_lines


def is_probable_table_of_contents(page_lines: List[str], page_text: str) -> bool:
    """Heuristically detect table-of-contents or navigation pages."""

    if not page_lines:
        return True

    top_text = " ".join(page_lines[:8]).lower()
    if "table of contents" in top_text:
        return True

    if page_lines and page_lines[0].strip().lower() == "contents":
        return True

    dot_leader_count = sum(1 for line in page_lines if re.search(r"\.{3,}", line))
    page_number_endings = sum(1 for line in page_lines if re.search(r"\s\d{1,4}$", line))
    short_line_count = sum(1 for line in page_lines if len(line) < 80)

    if dot_leader_count >= 4 and short_line_count >= 6:
        return True

    if page_number_endings >= 8 and short_line_count >= 12:
        return True

    return False


def is_probable_low_information_page(page_text: str) -> bool:
    """Detect pages that are too low-information to be useful for retrieval."""

    if len(page_text) < 120:
        return True
    if alpha_ratio(page_text) < 0.35:
        return True
    return False


def detect_section_heading(page_lines: List[str]) -> Optional[str]:
    """Extract a conservative section heading from the top of a clean page."""

    for line in page_lines[:6]:
        stripped = line.strip()
        if not stripped:
            continue
        if len(stripped) < 4 or len(stripped) > 120:
            continue
        if "table of contents" in stripped.lower():
            continue
        if re.search(r"\.{3,}", stripped):
            continue
        if re.search(r"\b\d{4}\b", stripped):
            continue
        if stripped.isupper() or re.match(r"^[A-Z][A-Za-z0-9/&,\-\s]{3,}$", stripped):
            return stripped
    return None


def extract_pdf_pages(pdf_path: Path, fallback_record: FileRecord) -> List[PageRecord]:
    """Extract clean page-level text and QA flags from one PDF."""

    page_records: List[PageRecord] = []

    try:
        with fitz.open(pdf_path) as document:
            raw_page_lines: List[List[str]] = []

            for page_index in range(len(document)):
                raw_text = document.load_page(page_index).get_text("text")
                raw_lines = [line.strip() for line in raw_text.splitlines() if line.strip()]
                raw_page_lines.append(raw_lines)

            repeated_edge_lines = detect_repeated_edge_lines(raw_page_lines)

            for page_index, raw_lines in enumerate(raw_page_lines):
                page_text_raw = normalise_whitespace("\n".join(raw_lines))
                cleaned_lines = clean_page_lines(
                    raw_lines=raw_lines,
                    repeated_edge_lines=repeated_edge_lines,
                    strip_repeated_headers_footers=CONFIG["strip_repeated_headers_footers"],
                )
                page_text = normalise_whitespace("\n".join(cleaned_lines))

                qa_flags: List[str] = []
                is_excluded = False
                exclusion_reason: Optional[str] = None

                if not page_text:
                    qa_flags.append("empty_after_cleaning")
                    is_excluded = True
                    exclusion_reason = "empty_after_cleaning"

                if (
                    not is_excluded
                    and CONFIG["drop_table_of_contents_pages"]
                    and is_probable_table_of_contents(cleaned_lines, page_text)
                ):
                    qa_flags.append("table_of_contents")
                    is_excluded = True
                    exclusion_reason = "table_of_contents"

                if not is_excluded and is_probable_low_information_page(page_text):
                    qa_flags.append("low_information_page")
                    is_excluded = True
                    exclusion_reason = "low_information_page"

                section = None if is_excluded else detect_section_heading(cleaned_lines)

                page_records.append(
                    PageRecord(
                        firm_name=fallback_record.firm_name,
                        fiscal_year=fallback_record.fiscal_year,
                        source_file=fallback_record.source_file,
                        page_number=page_index + 1,
                        section=section,
                        page_text=page_text,
                        page_text_raw=page_text_raw,
                        is_excluded=is_excluded,
                        exclusion_reason=exclusion_reason,
                        qa_flags=qa_flags,
                    )
                )
    except Exception as error:  # noqa: BLE001
        logger.warning("Failed to read PDF %s: %s", pdf_path, error)

    return page_records


def build_page_summary(pages_df: pd.DataFrame) -> pd.DataFrame:
    """Build a small page-level QA summary table."""

    if pages_df.empty:
        return pd.DataFrame()

    summary_rows = []
    for firm_name, firm_df in pages_df.groupby("firm_name", dropna=False):
        summary_rows.append(
            {
                "firm_name": firm_name,
                "pages_total": len(firm_df),
                "pages_excluded": int(firm_df["is_excluded"].sum()),
                "pages_kept": int((~firm_df["is_excluded"]).sum()),
                "toc_pages": int((firm_df["exclusion_reason"] == "table_of_contents").sum()),
                "low_info_pages": int((firm_df["exclusion_reason"] == "low_information_page").sum()),
            }
        )
    return pd.DataFrame(summary_rows)

## 8. Chunking and Chunk-Level QA

The new chunking logic is designed to avoid the problems seen in the earlier Intel run:

- chunks should not start mid-word
- overlap should not duplicate the same text awkwardly
- low-information chunks should be filtered before indexing

Chunking happens within each page so traceability remains clear.

In [26]:
def split_text_into_units(paragraph: str) -> List[str]:
    """Split a paragraph into sentence-like units for cleaner chunk boundaries."""

    paragraph = normalise_whitespace(paragraph)
    if not paragraph:
        return []

    sentence_candidates = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9(])", paragraph)
    units = [candidate.strip() for candidate in sentence_candidates if candidate.strip()]

    if len(units) == 1 and len(paragraph) > CONFIG["chunk_size_chars"]:
        # Fallback for very long blocks with poor sentence punctuation.
        fallback_units = re.split(r"(?<=;)\s+|(?<=:)\s+|(?<=,)\s+(?=[A-Z])", paragraph)
        units = [candidate.strip() for candidate in fallback_units if candidate.strip()]

    return units or [paragraph]


def split_page_text_into_units(page_text: str) -> List[str]:
    """Split a clean page into sentence-like units while roughly preserving paragraphs."""

    units: List[str] = []
    paragraphs = [paragraph.strip() for paragraph in re.split(r"\n{2,}", page_text) if paragraph.strip()]

    for paragraph in paragraphs:
        paragraph_units = split_text_into_units(paragraph)
        units.extend(paragraph_units)

    return units


def build_chunks_from_units(
    units: List[str],
    chunk_size_chars: int,
    chunk_overlap_chars: int,
    min_chunk_chars: int,
) -> List[str]:
    """Build overlapping chunks from sentence-like units."""

    if not units:
        return []

    chunks: List[str] = []
    current_units: List[str] = []
    current_length = 0

    for unit in units:
        projected_length = current_length + len(unit) + (1 if current_units else 0)
        if projected_length <= chunk_size_chars:
            current_units.append(unit)
            current_length = projected_length
            continue

        if current_units:
            chunk_text = normalise_whitespace(" ".join(current_units))
            if len(chunk_text) >= min_chunk_chars:
                chunks.append(chunk_text)

        overlap_units: List[str] = []
        overlap_length = 0
        for previous_unit in reversed(current_units):
            additional_length = len(previous_unit) + (1 if overlap_units else 0)
            if overlap_length + additional_length > chunk_overlap_chars:
                break
            overlap_units.insert(0, previous_unit)
            overlap_length += additional_length

        current_units = overlap_units + [unit]
        current_length = len(normalise_whitespace(" ".join(current_units)))

    if current_units:
        chunk_text = normalise_whitespace(" ".join(current_units))
        if len(chunk_text) >= min_chunk_chars:
            chunks.append(chunk_text)

    return chunks


def chunk_quality_flags(chunk_text: str) -> List[str]:
    """Assign QA flags to chunks that look noisy or unhelpful."""

    flags: List[str] = []
    lowered = chunk_text.lower()

    if "table of contents" in lowered:
        flags.append("table_of_contents")

    if alpha_ratio(chunk_text) < 0.45:
        flags.append("low_alpha_ratio")

    if re.search(r"\.{3,}", chunk_text):
        flags.append("dot_leaders")

    if len(chunk_text) < CONFIG["min_chunk_chars"]:
        flags.append("too_short")

    return flags


def build_chunk_id(
    firm_name: Optional[str],
    fiscal_year: Optional[int],
    source_file: str,
    page_number: int,
    passage: str,
) -> str:
    """Create a deterministic chunk identifier from metadata and passage text."""

    raw_value = "||".join(
        [
            str(firm_name or ""),
            str(fiscal_year or ""),
            source_file,
            str(page_number),
            passage,
        ]
    )
    return sha1(raw_value.encode("utf-8")).hexdigest()


def create_chunks_from_pages(pages_df: pd.DataFrame) -> pd.DataFrame:
    """Create chunk records from the clean page DataFrame."""

    chunk_records: List[ChunkRecord] = []

    if pages_df.empty:
        return pd.DataFrame()

    clean_pages_df = pages_df.loc[~pages_df["is_excluded"]].copy()

    for page_row in tqdm(
        clean_pages_df.itertuples(index=False),
        total=len(clean_pages_df),
        desc="Chunking clean pages",
    ):
        units = split_page_text_into_units(page_row.page_text)
        page_chunks = build_chunks_from_units(
            units=units,
            chunk_size_chars=CONFIG["chunk_size_chars"],
            chunk_overlap_chars=CONFIG["chunk_overlap_chars"],
            min_chunk_chars=CONFIG["min_chunk_chars"],
        )

        for chunk_text in page_chunks:
            qa_flags = chunk_quality_flags(chunk_text)
            is_excluded = CONFIG["filter_low_quality_chunks"] and any(
                flag in {"table_of_contents", "low_alpha_ratio", "dot_leaders", "too_short"}
                for flag in qa_flags
            )
            exclusion_reason = qa_flags[0] if is_excluded and qa_flags else None

            chunk_records.append(
                ChunkRecord(
                    firm_name=page_row.firm_name,
                    fiscal_year=page_row.fiscal_year,
                    source_file=page_row.source_file,
                    page_number=page_row.page_number,
                    section=page_row.section,
                    chunk_id=build_chunk_id(
                        firm_name=page_row.firm_name,
                        fiscal_year=page_row.fiscal_year,
                        source_file=page_row.source_file,
                        page_number=page_row.page_number,
                        passage=chunk_text,
                    ),
                    passage=chunk_text,
                    qa_flags=qa_flags,
                    is_excluded=is_excluded,
                    exclusion_reason=exclusion_reason,
                )
            )

    chunks_df = pd.DataFrame([asdict(record) for record in chunk_records])

    if not chunks_df.empty:
        chunks_df = chunks_df.drop_duplicates(subset=["chunk_id"]).reset_index(drop=True)

    return chunks_df


def build_chunk_summary(chunks_df: pd.DataFrame) -> pd.DataFrame:
    """Build a small chunk QA summary table."""

    if chunks_df.empty:
        return pd.DataFrame()

    summary_rows = []
    for firm_name, firm_df in chunks_df.groupby("firm_name", dropna=False):
        summary_rows.append(
            {
                "firm_name": firm_name,
                "chunks_total": len(firm_df),
                "chunks_excluded": int(firm_df["is_excluded"].sum()),
                "chunks_indexed": int((~firm_df["is_excluded"]).sum()),
            }
        )
    return pd.DataFrame(summary_rows)

## 9. Embeddings, Vector Indexing, and Retrieval

Retrieval is broadened in this final version in two ways:

- each theme now has multiple queries rather than just one
- retrieval happens inside each company corpus instead of one mixed global index

This gives better recall while preserving company-specific context and cleaner exports.

In [27]:
def load_embedding_model(model_name: str) -> SentenceTransformer:
    """Load the sentence-transformer model used for chunk and query embeddings."""

    logger.info("Loading embedding model: %s", model_name)
    return SentenceTransformer(model_name)


def embed_texts(
    texts: Sequence[str],
    embedding_model: SentenceTransformer,
    batch_size: int,
) -> np.ndarray:
    """Embed texts as normalized float32 vectors for FAISS."""

    embeddings = embedding_model.encode(
        list(texts),
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return embeddings.astype("float32")


def save_faiss_index(index: faiss.Index, index_path: Path) -> None:
    """Persist a FAISS index to disk."""

    faiss.write_index(index, str(index_path))


def load_faiss_index(index_path: Path) -> faiss.Index:
    """Load a FAISS index from disk."""

    return faiss.read_index(str(index_path))


def build_or_load_vector_store(
    company_name: str,
    chunks_df: pd.DataFrame,
    embedding_model: SentenceTransformer,
    output_paths: Dict[str, Path],
) -> Tuple[faiss.Index, pd.DataFrame]:
    """Build or load the per-company vector store."""

    index_path = output_paths["faiss_index_path"]
    metadata_path = output_paths["faiss_metadata_path"]

    if (
        not CONFIG["rebuild_index"]
        and index_path.exists()
        and metadata_path.exists()
    ):
        logger.info("Loading existing vector store for %s", company_name)
        return load_faiss_index(index_path), load_pickle(metadata_path)

    indexable_chunks = chunks_df.loc[~chunks_df["is_excluded"]].reset_index(drop=True)
    if indexable_chunks.empty:
        raise ValueError(f"No clean chunks available to index for {company_name}.")

    embeddings = embed_texts(
        texts=indexable_chunks["passage"].tolist(),
        embedding_model=embedding_model,
        batch_size=CONFIG["embedding_batch_size"],
    )

    vector_dimension = embeddings.shape[1]
    index = faiss.IndexFlatIP(vector_dimension)
    index.add(embeddings)

    save_faiss_index(index, index_path)
    save_pickle(indexable_chunks, metadata_path)

    return index, indexable_chunks


def build_company_query_pack(company_name: str) -> List[Dict[str, str]]:
    """Build the query pack for one company, including optional scope hints."""

    scope_suffix = COMPANY_SCOPE_RULES.get(company_name, {}).get("retrieval_scope_suffix", "").strip()
    company_queries: List[Dict[str, str]] = []

    for query_row in QUERY_PACK:
        query_text = query_row["query_text"]
        if scope_suffix:
            query_text = f"{query_text}. {scope_suffix}"

        company_queries.append(
            {
                "retrieval_theme": query_row["retrieval_theme"],
                "retrieval_query": query_row["retrieval_query"],
                "query_text": query_text,
            }
        )

    return company_queries


def retrieve_top_k_chunks(
    query_pack: List[Dict[str, str]],
    embedding_model: SentenceTransformer,
    vector_index: faiss.Index,
    chunk_metadata_df: pd.DataFrame,
) -> pd.DataFrame:
    """Run the broader query pack against the company vector index."""

    retrieval_rows: List[Dict[str, Any]] = []

    for query_row in tqdm(query_pack, desc="Running retrieval queries"):
        query_vector = embed_texts(
            texts=[query_row["query_text"]],
            embedding_model=embedding_model,
            batch_size=1,
        )
        scores, indices = vector_index.search(query_vector, CONFIG["top_k_retrieval"])

        for rank, (score, chunk_index) in enumerate(zip(scores[0], indices[0]), start=1):
            if chunk_index < 0:
                continue

            chunk_row = chunk_metadata_df.iloc[int(chunk_index)].to_dict()
            retrieval_rows.append(
                {
                    **chunk_row,
                    "retrieval_theme": query_row["retrieval_theme"],
                    "retrieval_query": query_row["retrieval_query"],
                    "retrieval_query_text": query_row["query_text"],
                    "retrieval_rank": rank,
                    "retrieval_score": float(score),
                    "passage_norm_hash": sha1(
                        soft_normalize_passage(chunk_row["passage"]).encode("utf-8")
                    ).hexdigest(),
                }
            )

    return pd.DataFrame(retrieval_rows)


def deduplicate_retrieved_chunks(retrieval_df: pd.DataFrame) -> pd.DataFrame:
    """Deduplicate retrieval results before classification."""

    if retrieval_df.empty:
        return retrieval_df.copy()

    deduped_df = (
        retrieval_df.sort_values(
            by=["retrieval_score", "retrieval_rank"],
            ascending=[False, True],
        )
        .drop_duplicates(subset=["chunk_id"], keep="first")
        .drop_duplicates(subset=["passage_norm_hash"], keep="first")
        .reset_index(drop=True)
    )

    return deduped_df

## 10. LLM Classification and Label Normalization

The model is used only as a classifier. The passage text is not rewritten.

The final `strategy_category` must be:

- one of the exact E1-E7 controlled labels, or
- an `I-*` inductive code if the passage is relevant but does not fit the framework

A post-classification normalization step enforces this rule even if the raw LLM output drifts.

In [28]:
def get_openai_client(api_key_env_var: str) -> OpenAI:
    """Create an OpenAI client from an environment variable."""

    api_key = os.getenv(api_key_env_var)
    if not api_key:
        raise EnvironmentError(
            f"Environment variable '{api_key_env_var}' is not set. "
            "Set your API key before running classification."
        )
    return OpenAI(api_key=api_key)


_thread_local_state = threading.local()


def get_thread_local_openai_client(api_key_env_var: str) -> OpenAI:
    """Return one OpenAI client per worker thread for safer concurrent requests."""

    client = getattr(_thread_local_state, "openai_client", None)
    client_env = getattr(_thread_local_state, "api_key_env_var", None)

    if client is None or client_env != api_key_env_var:
        client = get_openai_client(api_key_env_var)
        _thread_local_state.openai_client = client
        _thread_local_state.api_key_env_var = api_key_env_var
        logger.info(
            "Initialized OpenAI client in worker thread %s",
            threading.current_thread().name,
        )

    return client


def inductive_code(raw_label: Optional[str]) -> str:
    """Convert a raw label into a valid `I-*` inductive code."""

    raw_label = normalise_whitespace(str(raw_label or "uncategorised"))
    raw_label = re.sub(r"(?i)^i[\s\-_]*", "", raw_label).strip()
    preferred_code = match_preferred_inductive_code(raw_label)
    if preferred_code:
        return preferred_code
    raw_slug = slugify(raw_label).replace("_", "-")
    return f"I-{raw_slug or 'uncategorised'}"


def match_preferred_inductive_code(raw_value: Optional[str]) -> Optional[str]:
    """Map common inductive themes to preferred exact `I-*` labels."""

    if raw_value is None:
        return None

    lowered = normalize_for_matching(str(raw_value)).replace("_", " ")
    exact_map = {
        normalize_for_matching(code).replace("_", " "): code
        for code in PREFERRED_INDUCTIVE_CODES
    }
    if lowered in exact_map:
        return exact_map[lowered]

    pattern_map: List[Tuple[List[str], str]] = [
        (["subsidy", "grant", "government support", "government incentive", "public incentive", "public funding", "state aid", "chips act", "industrial policy", "tax credit"], "I-GovernmentSubsidy"),
        (["export control", "export compliance", "licensing", "entity list", "sanction", "trade compliance", "trade restriction", "government restriction"], "I-ExportControlCompliance"),
        (["stockpil", "strategic reserve", "material reserve", "raw material reserve", "critical material inventory", "inventory reserve", "buffer of critical materials"], "I-MaterialStockpiling"),
    ]

    for keywords, code in pattern_map:
        if any(keyword in lowered for keyword in keywords):
            return code

    return None


def normalize_strategy_category(
    raw_value: Optional[str],
    retrieval_theme: Optional[str],
) -> str:
    """Normalize raw model output into the controlled category set."""

    if not raw_value:
        fallback_category = THEME_TO_CONTROLLED_CATEGORY.get(retrieval_theme or "", "E7 SCRM and Visibility")
        return fallback_category

    raw_text = str(raw_value)
    lowered = normalize_for_matching(raw_text).replace("_", " ")

    exact_map = {
        normalize_for_matching(category).replace("_", " "): category
        for category in CONTROLLED_STRATEGY_CATEGORIES
    }

    if lowered in exact_map:
        return exact_map[lowered]

    preferred_inductive_code = match_preferred_inductive_code(raw_value)
    if preferred_inductive_code:
        return preferred_inductive_code

    pattern_map: List[Tuple[List[str], str]] = [
        (["operational buffer", "inventory", "safety stock", "buffer stock", "capacity buffer"], "E1 Operational Buffers"),
        (["footprint", "geographic diversification", "manufacturing expansion", "fab location", "nearshoring", "regional diversification"], "E2 Footprint Diversification"),
        (["dual sourcing", "alternative supplier", "second source", "backup supply", "supplier diversification", "sourcing"], "E3 Supply Option Diversification"),
        (["distribution", "logistics", "freight", "shipment", "channel management", "transport"], "E4 Robust Distribution"),
        (["standardisation", "standardization", "sku", "common design", "platform architecture", "modular design"], "E5 Product Standardisation"),
        (["partnership", "collaboration", "long term supply", "capacity reservation", "ecosystem", "foundry collaboration"], "E6 Partner Network Strengthening"),
        (["risk management", "supplier monitoring", "risk monitoring", "supply chain visibility", "business continuity", "contingency planning", "risk assessment", "control tower", "early warning", "scenario planning", "continuity planning"], "E7 SCRM and Visibility"),
    ]

    for keywords, normalized_category in pattern_map:
        if any(keyword in lowered for keyword in keywords):
            return normalized_category

    if re.match(r"(?i)^i[\s\-_]", raw_text.strip()):
        return inductive_code(raw_text)

    return inductive_code(raw_value)


def normalize_secondary_category(
    raw_value: Optional[str],
    retrieval_theme: Optional[str],
) -> str:
    """Normalize `secondary_category` to either 0 or the same E1-E7 framework."""

    if raw_value is None:
        return "0"

    lowered = normalize_for_matching(str(raw_value)).replace("_", " ")
    if lowered in {"0", "none", "null", "na", "n a", "missing", "other", "n/a"}:
        return "0"

    exact_map = {
        normalize_for_matching(category).replace("_", " "): category
        for category in CONTROLLED_STRATEGY_CATEGORIES
    }
    if lowered in exact_map:
        return exact_map[lowered]

    for category in CONTROLLED_STRATEGY_CATEGORIES:
        normalized_category = normalize_strategy_category(raw_value, retrieval_theme)
        if normalized_category == category:
            return normalized_category

    return "0"


def normalize_orientation(raw_value: Optional[str]) -> str:
    """Normalize `orientation` to proactive, reactive, or descriptive."""

    if raw_value is None:
        return "descriptive"

    lowered = normalize_for_matching(str(raw_value)).replace("_", " ")

    proactive_keywords = [
        "proactive", "anticipatory", "preventive", "preparedness", "preemptive", "forward looking", "long term"
    ]
    reactive_keywords = [
        "reactive", "response", "responding", "mitigation after", "contingency response", "crisis response"
    ]
    descriptive_keywords = [
        "descriptive", "observational", "context", "background", "narrative", "general", "informational"
    ]

    if any(keyword in lowered for keyword in proactive_keywords):
        return "proactive"
    if any(keyword in lowered for keyword in reactive_keywords):
        return "reactive"
    if any(keyword in lowered for keyword in descriptive_keywords):
        return "descriptive"

    return "descriptive"


def normalize_geopolitical_trigger(raw_value: Optional[str]) -> str:
    """Normalize geopolitical triggers to a small controlled list or blank."""

    if raw_value is None:
        return ""

    lowered = normalize_for_matching(str(raw_value)).replace("_", " ")
    if lowered in {"", "0", "none", "null", "na", "n a", "missing", "other", "n/a"}:
        return ""

    exact_map = {
        normalize_for_matching(trigger).replace("_", " "): trigger
        for trigger in ALLOWED_GEOPOLITICAL_TRIGGERS
    }
    if lowered in exact_map:
        return exact_map[lowered]

    pattern_map: List[Tuple[List[str], str]] = [
        (["covid", "pandemic", "coronavirus"], "COVID-19 pandemic"),
        (["ukraine", "russia", "russian invasion"], "Russia-Ukraine war"),
        (["us china trade", "u s china trade", "trade war", "tariff", "u s china tension"], "U.S.-China trade tensions"),
        (["export control", "chip restriction", "china restriction", "october 2022 controls", "technology restriction"], "U.S. export controls on China"),
        (["chips act", "public subsidy", "government subsidy", "state aid", "grant", "incentive"], "CHIPS Act and public subsidy programs"),
        (["taiwan strait", "cross strait", "taiwan tension"], "Taiwan Strait tensions"),
        (["entity list", "sanction", "blacklist", "license requirement"], "Sanctions or entity-list restrictions"),
        (["energy crisis", "critical material", "raw material", "neon", "gas shortage", "material disruption"], "Critical-material or energy supply disruption"),
    ]

    for keywords, trigger in pattern_map:
        if any(keyword in lowered for keyword in keywords):
            return trigger

    return ""


def build_classification_prompt(passage_row: pd.Series) -> str:
    """Build the final classification prompt used for one retrieved chunk."""

    company_scope_text = COMPANY_SCOPE_RULES.get(
        str(passage_row.get("firm_name", "")),
        {},
    ).get("classification_scope", "")

    allowed_categories_text = "\n".join(f"- {category}" for category in CONTROLLED_STRATEGY_CATEGORIES)
    preferred_inductive_text = "\n".join(f"- {code}" for code in PREFERRED_INDUCTIVE_CODES)
    allowed_triggers_text = "\n".join(f"- {trigger}" for trigger in ALLOWED_GEOPOLITICAL_TRIGGERS)

    instructions = textwrap.dedent(
        f"""
        You are classifying an original annual-report passage for a semiconductor supply-chain thesis.

        Important rules:
        1. Do not rewrite, summarize, shorten, or paraphrase the passage.
        2. Your task is classification only.
        3. Return exactly one JSON object and nothing else.
        4. The JSON object must contain exactly these keys:
           relevant
           strategy_category
           secondary_category
           geopolitical_trigger
           orientation
           main_point
           confidence
        5. If relevant is true, `strategy_category` must be either:
           - one of these exact labels:
        {allowed_categories_text}
           - or, if the passage is relevant but does not fit E1-E7, prefer one of these exact inductive labels first:
        {preferred_inductive_text}
           - if none of those fit, use another inductive code formatted as I-<slug>
        6. `secondary_category` must be either:
           - `0`
           - or one of the exact E1-E7 labels above
        7. `orientation` must be exactly one of:
           - proactive
           - reactive
           - descriptive
        8. `geopolitical_trigger` must be either an empty string if no specific trigger is clearly identifiable,
           or one of these exact labels:
        {allowed_triggers_text}
        9. If the passage is not materially relevant to semiconductor supply-chain strategy,
           resilience, sourcing, manufacturing footprint, logistics, partnerships, or risk
           monitoring, return relevant=false.
        10. Use E7 SCRM and Visibility only when the passage clearly describes monitoring,
            visibility, business continuity, contingency planning, early warning, or formal
            supply-chain risk management mechanisms.
        11. Do not use E7 only because a passage mentions geopolitics, trade restrictions,
            regulation, tariffs, or government policy.
        12. Prefer I-GovernmentSubsidy for grants, subsidies, tax credits, public incentives,
            CHIPS-type support, or industrial-policy funding.
        13. Prefer I-ExportControlCompliance for export controls, licensing restrictions,
            entity-list rules, sanctions, and compliance with government trade restrictions.
        14. Prefer I-MaterialStockpiling for strategic stockpiling or reserve-building of
            critical materials rather than routine working inventory.
        15. `confidence` must be numeric between 0 and 1.
        16. Use null only when a field is truly not inferable, but prefer the constrained values
            above wherever possible.
        """
    ).strip()

    metadata_block = textwrap.dedent(
        f"""
        Metadata:
        - firm_name: {passage_row.get("firm_name")}
        - fiscal_year: {passage_row.get("fiscal_year")}
        - source_file: {passage_row.get("source_file")}
        - page_number: {passage_row.get("page_number")}
        - section: {passage_row.get("section")}
        - retrieval_theme: {passage_row.get("retrieval_theme")}
        - retrieval_query: {passage_row.get("retrieval_query")}
        """
    ).strip()

    scope_block = f"Company-specific scope rule:\n{company_scope_text}" if company_scope_text else ""

    return f"{instructions}\n\n{metadata_block}\n\n{scope_block}\n\nPassage:\n{passage_row.get('passage')}"


def extract_json_object(text: str) -> Optional[Dict[str, Any]]:
    """Extract the first JSON object from a text response."""

    text = text.strip()
    if not text:
        return None

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        return None

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def validate_classification_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Validate the raw classification payload before normalization."""

    if set(payload.keys()) != set(EXPECTED_CLASSIFICATION_KEYS):
        raise ValueError(
            f"Invalid JSON keys. Expected exactly {EXPECTED_CLASSIFICATION_KEYS}, got {list(payload.keys())}"
        )

    if not isinstance(payload["relevant"], bool):
        raise ValueError("'relevant' must be a boolean.")

    if payload["orientation"] is not None and not isinstance(payload["orientation"], str):
        raise ValueError("'orientation' must be a string or null.")

    if payload["secondary_category"] is not None and not isinstance(payload["secondary_category"], str):
        raise ValueError("'secondary_category' must be a string or null.")

    if payload["geopolitical_trigger"] is not None and not isinstance(payload["geopolitical_trigger"], str):
        raise ValueError("'geopolitical_trigger' must be a string or null.")

    if not isinstance(payload["confidence"], (int, float)):
        raise ValueError("'confidence' must be numeric.")

    confidence_value = float(payload["confidence"])
    if not 0 <= confidence_value <= 1:
        raise ValueError("'confidence' must be between 0 and 1.")

    return {
        "relevant": payload["relevant"],
        "strategy_category": payload["strategy_category"],
        "secondary_category": payload["secondary_category"],
        "geopolitical_trigger": payload["geopolitical_trigger"],
        "orientation": payload["orientation"],
        "main_point": payload["main_point"],
        "confidence": confidence_value,
    }


def request_openai_json_response(client: OpenAI, model_name: str, prompt: str) -> str:
    """Request a raw model response from OpenAI."""

    response = client.responses.create(
        model=model_name,
        input=prompt,
    )
    return response.output_text


def classify_chunk_with_retries(
    passage_row: pd.Series,
    client: OpenAI,
    model_name: str,
    max_attempts: int = 2,
) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
    """Classify one chunk and retry once with a repair prompt if needed."""

    prompt = build_classification_prompt(passage_row)
    raw_response_text = ""

    for attempt_number in range(1, max_attempts + 1):
        try:
            if attempt_number == 1:
                raw_response_text = request_openai_json_response(client, model_name, prompt)
            else:
                repair_prompt = textwrap.dedent(
                    f"""
                    The following output was invalid. Repair it into valid JSON only.

                    Required keys:
                    {EXPECTED_CLASSIFICATION_KEYS}

                    Rules:
                    - return exactly one JSON object
                    - do not add markdown or commentary
                    - preserve the original classification intent if possible
                    - relevant must be boolean
                    - confidence must be numeric between 0 and 1
                    - orientation must be proactive, reactive, or descriptive
                    - secondary_category must be 0 or one of the exact E1-E7 labels
                    - geopolitical_trigger must be an empty string or one of the exact allowed trigger labels

                    Invalid output:
                    {raw_response_text}
                    """
                ).strip()
                raw_response_text = request_openai_json_response(client, model_name, repair_prompt)

            parsed_payload = extract_json_object(raw_response_text)
            if parsed_payload is None:
                raise ValueError("No valid JSON object found in the model response.")

            return validate_classification_payload(parsed_payload), None

        except Exception as error:  # noqa: BLE001
            if attempt_number == max_attempts:
                return None, f"Classification failed after {max_attempts} attempts: {error}"

    return None, "Unexpected classification failure."


def classify_chunk_record(
    row_dict: Dict[str, Any],
    model_name: str,
    api_key_env_var: str,
) -> Dict[str, Any]:
    """Classify one retrieved chunk record inside a worker thread."""

    row_series = pd.Series(row_dict)
    client = get_thread_local_openai_client(api_key_env_var)
    payload, failure_message = classify_chunk_with_retries(
        passage_row=row_series,
        client=client,
        model_name=model_name,
    )

    base_record = row_series.to_dict()

    if payload is None:
        logger.warning(
            "Classification failed for chunk %s: %s",
            base_record["chunk_id"],
            failure_message,
        )
        return {
            **base_record,
            "classification_failed": True,
            "classification_error": failure_message,
            "relevant": None,
            "strategy_category_raw": None,
            "strategy_category": None,
            "secondary_category": None,
            "geopolitical_trigger": None,
            "orientation": None,
            "main_point": None,
            "confidence": None,
        }

    normalized_category = (
        normalize_strategy_category(payload["strategy_category"], row_series.get("retrieval_theme"))
        if payload["relevant"]
        else None
    )
    normalized_secondary_category = (
        normalize_secondary_category(payload["secondary_category"], row_series.get("retrieval_theme"))
        if payload["relevant"]
        else "0"
    )
    normalized_orientation = (
        normalize_orientation(payload["orientation"])
        if payload["relevant"]
        else "descriptive"
    )
    normalized_geopolitical_trigger = (
        normalize_geopolitical_trigger(payload["geopolitical_trigger"])
        if payload["relevant"]
        else ""
    )

    return {
        **base_record,
        "classification_failed": False,
        "classification_error": None,
        "relevant": payload["relevant"],
        "strategy_category_raw": payload["strategy_category"],
        "strategy_category": normalized_category,
        "secondary_category": normalized_secondary_category,
        "geopolitical_trigger": normalized_geopolitical_trigger,
        "orientation": normalized_orientation,
        "main_point": payload["main_point"],
        "confidence": payload["confidence"],
    }


def classify_retrieved_chunks(
    retrieved_df: pd.DataFrame,
    model_name: str,
    api_key_env_var: str,
    max_workers: int,
) -> pd.DataFrame:
    """Classify deduplicated retrieved chunks with a concurrent worker pool."""

    if retrieved_df.empty:
        return pd.DataFrame(columns=list(retrieved_df.columns) + EXPECTED_CLASSIFICATION_KEYS)

    row_dicts = retrieved_df.to_dict(orient="records")
    indexed_results: List[Tuple[int, Dict[str, Any]]] = []
    progress_log_interval = max(10, min(50, len(row_dicts) // max(max_workers, 1) or 1))

    logger.info(
        "Starting classification pool for %s retrieved chunks with up to %s worker threads.",
        len(row_dicts),
        max_workers,
    )

    with ThreadPoolExecutor(max_workers=max_workers, thread_name_prefix="classifier") as executor:
        future_to_index = {
            executor.submit(
                classify_chunk_record,
                row_dict=row_dict,
                model_name=model_name,
                api_key_env_var=api_key_env_var,
            ): index
            for index, row_dict in enumerate(row_dicts)
        }

        logger.info(
            "Submitted %s classification tasks to the worker pool.",
            len(future_to_index),
        )
        completed_count = 0

        for future in tqdm(
            as_completed(future_to_index),
            total=len(future_to_index),
            desc=f"Classifying retrieved chunks ({max_workers} workers)",
        ):
            index = future_to_index[future]
            try:
                indexed_results.append((index, future.result()))
                completed_count += 1
                if completed_count % progress_log_interval == 0 or completed_count == len(future_to_index):
                    logger.info(
                        "Classification pool progress: %s/%s chunks completed.",
                        completed_count,
                        len(future_to_index),
                    )
            except Exception as error:  # noqa: BLE001
                row_dict = row_dicts[index]
                logger.warning(
                    "Unhandled worker failure for chunk %s: %s",
                    row_dict.get("chunk_id"),
                    error,
                )
                indexed_results.append(
                    (
                        index,
                        {
                            **row_dict,
                            "classification_failed": True,
                            "classification_error": f"Unhandled worker failure: {error}",
                            "relevant": None,
                            "strategy_category_raw": None,
                            "strategy_category": None,
                            "secondary_category": None,
                            "geopolitical_trigger": None,
                            "orientation": None,
                            "main_point": None,
                            "confidence": None,
                        },
                    )
                )
                completed_count += 1

    indexed_results.sort(key=lambda item: item[0])
    classification_rows = [result for _, result in indexed_results]
    logger.info(
        "Completed classification pool for %s chunks.",
        len(classification_rows),
    )
    return pd.DataFrame(classification_rows)


def build_final_export(classified_df: pd.DataFrame) -> pd.DataFrame:
    """Filter to relevant rows and arrange the final export columns."""

    required_columns = [
        "firm_name",
        "fiscal_year",
        "section",
        "page_number",
        "passage",
        "strategy_category",
        "secondary_category",
        "geopolitical_trigger",
        "orientation",
        "main_point",
        "confidence",
        "source_file",
        "chunk_id",
        "retrieval_query",
        "retrieval_rank",
    ]

    if classified_df.empty or "relevant" not in classified_df.columns:
        return pd.DataFrame(columns=required_columns)

    final_df = classified_df.loc[classified_df["relevant"] == True].copy()  # noqa: E712
    final_df = final_df.drop_duplicates(
        subset=["chunk_id", "retrieval_query", "retrieval_rank"]
    ).reset_index(drop=True)

    final_df = final_df.sort_values(
        by=["fiscal_year", "page_number", "retrieval_query"],
        ascending=[True, True, True],
    ).reset_index(drop=True)

    return final_df[required_columns]

## 11. Company-Level Orchestration

This section wraps the helper functions into one company-level pipeline so that:

- `single_company` mode and `full_corpus` mode share the same logic
- all intermediate artifacts can be saved per company
- final exports are naturally split into one workbook per company

In [29]:
def safe_value_counts(dataframe: pd.DataFrame, column_name: str) -> pd.Series:
    """Return value counts safely for empty or missing columns."""

    if dataframe.empty or column_name not in dataframe.columns:
        return pd.Series(dtype="int64")
    return dataframe[column_name].fillna("Missing").value_counts(dropna=False)


EXCEL_ILLEGAL_CHARACTER_RE = re.compile(r"[\x00-\x08\x0B-\x0C\x0E-\x1F]")


def _sanitize_for_excel(value: Any) -> Any:
    """Remove characters that Excel/openpyxl cannot write safely."""

    if not isinstance(value, str):
        return value

    cleaned_value = EXCEL_ILLEGAL_CHARACTER_RE.sub("", value)
    return cleaned_value[:32767]


def sanitize_dataframe_for_excel(dataframe: pd.DataFrame) -> pd.DataFrame:
    """Return a copy with all string-like columns cleaned for openpyxl."""

    sanitized_df = dataframe.copy()
    for column_name in sanitized_df.columns:
        if is_string_dtype(sanitized_df[column_name]):
            sanitized_df[column_name] = sanitized_df[column_name].map(_sanitize_for_excel)
    return sanitized_df


def export_company_excel(final_df: pd.DataFrame, output_path: Path) -> None:
    """Export the final company DataFrame to Excel."""

    output_path.parent.mkdir(parents=True, exist_ok=True)

    sanitized_df = sanitize_dataframe_for_excel(final_df)
    sanitized_df.to_excel(output_path, index=False, engine="openpyxl")


def run_company_pipeline(
    company_name: str,
    company_manifest_df: pd.DataFrame,
    embedding_model: SentenceTransformer,
    openai_client: Optional[OpenAI],
) -> Dict[str, Any]:
    """Run the full end-to-end pipeline for one company."""

    output_paths = build_company_output_paths(company_name)

    company_manifest_df.to_csv(output_paths["manifest_path"], index=False)

    # -------- Page extraction --------
    if output_paths["pages_path"].exists() and CONFIG["use_cached_pages"]:
        pages_df = load_pickle(output_paths["pages_path"])
    else:
        page_records: List[PageRecord] = []
        for file_row in tqdm(
            company_manifest_df.itertuples(index=False),
            total=len(company_manifest_df),
            desc=f"Extracting pages: {company_name}",
        ):
            fallback_record = FileRecord(
                firm_name=file_row.firm_name,
                fiscal_year=file_row.fiscal_year,
                source_file=file_row.source_file,
                folder_name=file_row.folder_name,
                file_name=file_row.file_name,
            )
            page_records.extend(extract_pdf_pages(Path(file_row.source_file), fallback_record))
        pages_df = pd.DataFrame([asdict(record) for record in page_records])
        save_pickle(pages_df, output_paths["pages_path"])

    # -------- Chunking --------
    if output_paths["chunks_path"].exists() and CONFIG["use_cached_chunks"]:
        chunks_df = load_pickle(output_paths["chunks_path"])
    else:
        chunks_df = create_chunks_from_pages(pages_df)
        save_pickle(chunks_df, output_paths["chunks_path"])

    # -------- Retrieval --------
    if output_paths["retrieval_path"].exists() and CONFIG["use_cached_retrieval"]:
        retrieval_df = load_pickle(output_paths["retrieval_path"])
    else:
        vector_index, indexed_chunks_df = build_or_load_vector_store(
            company_name=company_name,
            chunks_df=chunks_df,
            embedding_model=embedding_model,
            output_paths=output_paths,
        )
        retrieval_df = retrieve_top_k_chunks(
            query_pack=build_company_query_pack(company_name),
            embedding_model=embedding_model,
            vector_index=vector_index,
            chunk_metadata_df=indexed_chunks_df,
        )
        save_pickle(retrieval_df, output_paths["retrieval_path"])

    deduplicated_retrieval_df = deduplicate_retrieved_chunks(retrieval_df)

    # -------- Classification --------
    if not CONFIG["run_classification"]:
        classified_df = pd.DataFrame()
    elif output_paths["classification_path"].exists() and CONFIG["use_cached_classification"]:
        classified_df = load_pickle(output_paths["classification_path"])
    else:
        classified_df = classify_retrieved_chunks(
            retrieved_df=deduplicated_retrieval_df,
            model_name=CONFIG["openai_model_name"],
            api_key_env_var=CONFIG["openai_api_key_env_var"],
            max_workers=CONFIG["classification_max_workers"],
        )
        save_pickle(classified_df, output_paths["classification_path"])

    final_df = build_final_export(classified_df) if CONFIG["run_classification"] else pd.DataFrame()
    save_pickle(final_df, output_paths["final_path"])

    if CONFIG["write_company_excels"] and not final_df.empty:
        export_company_excel(final_df, output_paths["company_excel_path"])

    page_summary = build_page_summary(pages_df)
    chunk_summary = build_chunk_summary(chunks_df)

    company_summary = pd.DataFrame(
        [
            {
                "firm_name": company_name,
                "files_processed": len(company_manifest_df),
                "pages_total": 0 if pages_df.empty else len(pages_df),
                "pages_excluded": 0 if pages_df.empty else int(pages_df["is_excluded"].sum()),
                "chunks_total": 0 if chunks_df.empty else len(chunks_df),
                "chunks_indexed": 0 if chunks_df.empty else int((~chunks_df["is_excluded"]).sum()),
                "retrieved_rows": len(retrieval_df),
                "deduplicated_retrieval_rows": len(deduplicated_retrieval_df),
                "classification_rows": len(classified_df),
                "final_relevant_rows": len(final_df),
                "low_output_warning": bool(
                    CONFIG["run_classification"]
                    and len(final_df) < CONFIG["low_output_warning_threshold"]
                ),
            }
        ]
    )
    company_summary.to_csv(output_paths["summary_path"], index=False)

    if CONFIG["run_classification"] and len(final_df) < CONFIG["low_output_warning_threshold"]:
        logger.warning(
            "%s produced only %s final rows, which is below the configured warning threshold of %s.",
            company_name,
            len(final_df),
            CONFIG["low_output_warning_threshold"],
        )
    elif CONFIG["run_classification"] and len(final_df) >= 120:
        logger.info(
            "%s produced %s final rows. This is high-volume but plausible for a dense company corpus.",
            company_name,
            len(final_df),
        )

    return {
        "company_name": company_name,
        "manifest_df": company_manifest_df,
        "pages_df": pages_df,
        "page_summary_df": page_summary,
        "chunks_df": chunks_df,
        "chunk_summary_df": chunk_summary,
        "retrieval_df": retrieval_df,
        "deduplicated_retrieval_df": deduplicated_retrieval_df,
        "classified_df": classified_df,
        "final_df": final_df,
        "company_summary_df": company_summary,
        "output_paths": output_paths,
    }

## 12. Manifest Preview for the Current Run

This cell shows which files will be processed under the current configuration.
In `single_company` mode, this should show one firm across all matching years.

In [30]:
manifest_df = select_manifest_for_run(CONFIG)

print(f"Manifest rows: {len(manifest_df):,}")
if not manifest_df.empty:
    print(f"Companies in current run: {manifest_df['firm_name'].nunique(dropna=True)}")
    display(manifest_df.head(20))
    display(
        manifest_df["firm_name"]
        .value_counts(dropna=False)
        .rename("file_count")
        .to_frame()
    )

2026-04-14 11:53:28,247 | INFO | Discovered 10 PDFs across 10 companies

Manifest rows: 10
Companies in current run: 10

  firm_name  fiscal_year                                                        source_file folder_name          file_name
0      ASML         2017          /Users/paulkoslowsky/Github/Jakop/Data/ASML/ASML_2017.pdf        ASML      ASML_2017.pdf
1     Elmos         2017        /Users/paulkoslowsky/Github/Jakop/Data/Elmos/Elmos_2017.pdf       Elmos     Elmos_2017.pdf
2  Infineon         2017  /Users/paulkoslowsky/Github/Jakop/Data/Infineon/Infineon_2017.pdf    Infineon  Infineon_2017.pdf
3     Intel         2017        /Users/paulkoslowsky/Github/Jakop/Data/Intel/Intel_2017.pdf       Intel     Intel_2017.pdf
4  MediaTek         2017  /Users/paulkoslowsky/Github/Jakop/Data/Mediatek/MediaTek_2017.pdf    Mediatek  MediaTek_2017.pdf
5    Micron         2017      /Users/paulkoslowsky/Github/Jakop/Data/Micron/Micron_2017.pdf      Micron    Micron_2017.pdf
6       NXP         2017            /Users/paulkoslowsky/Github/Jakop/Data/NXP/NXP_2017.pdf         NXP       NXP_2017.pdf
7   Qualcom         2017    /Users/paulkoslowsky/Github/Jakop/Data/Qualcom/Qualcom_2017.pdf     Qualcom   Qualcom_2017.pdf
8   Samsung         2017    /Users/paulkoslowsky/Github/Jakop/Data/Samsung/Samsung_2017.pdf     Samsung   Samsung_2017.pdf
9      TSMC         2017          /Users/paulkoslowsky/Github/Jakop/Data/TSMC/TSMC_2017.pdf        TSMC      TSMC_2017.pdf

           file_count
firm_name
ASML                1
Elmos               1
Infineon            1
Intel               1
MediaTek            1
Micron              1
NXP                 1
Qualcom             1
Samsung             1
TSMC                1

## 13. Execute the Company-Level Pipeline

This cell runs the actual pipeline.

Behavior:

- in `single_company` mode, the notebook runs one firm across all available years
- in `full_corpus` mode, the notebook loops through all discovered companies

The same company-level function is used in both modes so testing and final production remain
aligned.

In [31]:
embedding_model = load_embedding_model(CONFIG["embedding_model_name"])

company_results: List[Dict[str, Any]] = []

for company_name, company_manifest_df in manifest_df.groupby("firm_name", dropna=False):
    if pd.isna(company_name):
        logger.warning("Skipping a manifest group with missing firm_name.")
        continue

    print(f"\nRunning pipeline for: {company_name}")
    result = run_company_pipeline(
        company_name=str(company_name),
        company_manifest_df=company_manifest_df.reset_index(drop=True),
        embedding_model=embedding_model,
        openai_client=None,
    )
    company_results.append(result)

print(f"\nCompleted pipeline runs for {len(company_results)} company/corpus groups.")

2026-04-14 11:53:34,358 | INFO | Loading embedding model: sentence-transformers/all-MiniLM-L6-v2

2026-04-14 11:53:34,380 | INFO | No device provided, using mps
2026-04-14 11:53:34,632 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:34,656 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/modules.json "HTTP/1.1 200 OK"
2026-04-14 11:53:34,822 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:34,845 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-04-14 11:53:34,848 | INFO | Loading SentenceTransformer model from sentence-transformers/all-MiniLM-L6-v2.
2026-04-14 11:53:34,989 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:35,011 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-04-14 11:53:35,157 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:35,180 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/README.md "HTTP/1.1 200 OK"
2026-04-14 11:53:35,349 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:35,370 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/modules.json "HTTP/1.1 200 OK"
2026-04-14 11:53:35,511 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:35,535 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-04-14 11:53:35,682 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-04-14 11:53:35,874 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:35,905 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6562.96it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-04-14 11:53:36,215 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-04-14 11:53:36,400 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-04-14 11:53:36,536 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-04-14 11:53:36,678 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-04-14 11:53:36,809 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:36,829 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-14 11:53:37,045 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:37,071 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json "HTTP/1.1 200 OK"
2026-04-14 11:53:37,216 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:37,237 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json "HTTP/1.1 200 OK"
2026-04-14 11:53:37,445 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:37,469 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-14 11:53:37,631 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-14 11:53:37,776 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-14 11:53:38,095 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-14 11:53:38,116 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-04-14 11:53:38,260 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"

Running pipeline for: ASML

Extracting pages: ASML: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
Chunking clean pages: 100%|██████████| 187/187 [00:00<00:00, 2274.57it/s]
Batches: 100%|██████████| 15/15 [00:02<00:00,  6.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 41.61it/s]0<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 80.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 190.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 58.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 79.12it/s]0<00:00, 45.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 175.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 171.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 174.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 161.39it/s]0<00:00, 59.28it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 48.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 168.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 160.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.98it/s]0<00:00, 56.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 54.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.43it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 54.52it/s]
2026-04-14 11:53:44,360 | INFO | Starting classification pool for 131 retrieved chunks with up to 40 worker threads.
2026-04-14 11:53:44,387 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:53:44,392 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:53:44,393 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:53:44,393 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:53:44,393 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:53:44,393 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:53:44,393 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:53:44,394 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:53:44,396 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:53:44,396 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:53:44,396 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:53:44,397 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:53:44,397 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:53:44,397 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:53:44,398 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:53:44,398 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:53:44,398 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:53:44,398 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:53:44,398 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:53:44,399 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:53:44,403 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:53:44,404 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:53:44,408 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:53:44,408 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:53:44,409 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:53:44,411 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:53:44,411 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:53:44,412 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:53:44,414 | INFO | Submitted 131 classification tasks to the worker pool.
2026-04-14 11:53:44,414 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:53:44,415 | INFO | Initialized OpenAI client in worker thread classifier_36
Classifying retrieved chunks (40 workers):   0%|          | 0/131 [00:00<?, ?it/s]2026-04-14 11:53:44,416 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:53:44,416 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:53:44,416 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:53:44,418 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:53:44,419 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:53:46,381 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,465 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,477 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/131 [00:02<04:25,  2.04s/it]2026-04-14 11:53:46,512 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,531 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,538 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,609 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   2%|▏         | 3/131 [00:02<01:13,  1.73it/s]2026-04-14 11:53:46,614 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,656 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,668 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,719 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,719 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   5%|▌         | 7/131 [00:02<00:25,  4.90it/s]2026-04-14 11:53:46,741 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,772 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,775 | INFO | Classification pool progress: 10/131 chunks completed.
2026-04-14 11:53:46,783 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,787 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,885 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,908 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  10%|▉         | 13/131 [00:02<00:12,  9.83it/s]2026-04-14 11:53:46,937 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:46,977 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,132 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,157 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,167 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  12%|█▏        | 16/131 [00:02<00:11, 10.30it/s]2026-04-14 11:53:47,218 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,409 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,412 | WARNING | Classification failed for chunk b024dba762731351f7b49b3b1a9bafbc6db8982a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:47,481 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,568 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,570 | WARNING | Classification failed for chunk 89da1149b98a563c0608e37b34b2ab6081bc36bf: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  15%|█▍        | 19/131 [00:03<00:12,  9.25it/s]2026-04-14 11:53:47,675 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,678 | INFO | Classification pool progress: 20/131 chunks completed.
2026-04-14 11:53:47,717 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  16%|█▌        | 21/131 [00:03<00:11,  9.94it/s]2026-04-14 11:53:47,783 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,785 | WARNING | Classification failed for chunk d7670ddd40400bcfab68ccc18ea8af0816d8a074: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:47,798 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,805 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,813 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,933 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:47,934 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  20%|█▉        | 26/131 [00:03<00:07, 13.26it/s]2026-04-14 11:53:47,969 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,041 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  22%|██▏       | 29/131 [00:03<00:06, 15.53it/s]2026-04-14 11:53:48,046 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,049 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,051 | INFO | Classification pool progress: 30/131 chunks completed.
2026-04-14 11:53:48,058 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,071 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,157 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,234 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,236 | WARNING | Classification failed for chunk 9d7bc33cea612d0fd77f3f1c5cbbe1656ed105b3: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  24%|██▍       | 32/131 [00:03<00:06, 15.51it/s]2026-04-14 11:53:48,287 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,338 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,457 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,458 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,463 | WARNING | Classification failed for chunk b8664aa1abd555790e5f5bcfc03c1518ed4d0a94: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  26%|██▌       | 34/131 [00:04<00:07, 13.38it/s]2026-04-14 11:53:48,490 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,580 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,582 | WARNING | Classification failed for chunk a101f7b06e8f77554021452a31f255f1083a65d8: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  27%|██▋       | 36/131 [00:04<00:06, 14.03it/s]2026-04-14 11:53:48,689 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,761 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,782 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,796 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  29%|██▉       | 38/131 [00:04<00:07, 12.45it/s]2026-04-14 11:53:48,842 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,867 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,880 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,883 | INFO | Classification pool progress: 40/131 chunks completed.
2026-04-14 11:53:48,886 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,982 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,983 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,983 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,984 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  31%|███▏      | 41/131 [00:04<00:06, 13.37it/s]2026-04-14 11:53:48,984 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:48,995 | WARNING | Classification failed for chunk d6e902f960bedb23657fd32fcf26aa4936e7daff: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:49,011 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,041 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,043 | WARNING | Classification failed for chunk fb377de90a4149f6faa8cc3e80afb7f55878f5ad: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:49,051 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,112 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,113 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,114 | WARNING | Classification failed for chunk eadca757b8291d7943f42124f928c1bcb7ad597c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  35%|███▌      | 46/131 [00:04<00:04, 19.17it/s]2026-04-14 11:53:49,128 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,136 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,159 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,165 | INFO | Classification pool progress: 50/131 chunks completed.
2026-04-14 11:53:49,166 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,212 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,296 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  40%|███▉      | 52/131 [00:04<00:03, 23.42it/s]2026-04-14 11:53:49,376 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,378 | WARNING | Classification failed for chunk fb98b78ea10ce13725fbc79336b1521bdff5819f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:49,506 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,507 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  42%|████▏     | 55/131 [00:05<00:03, 20.20it/s]2026-04-14 11:53:49,659 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,695 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,746 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:49,747 | WARNING | Classification failed for chunk c60fada4d2d6c70dfd2faec662a84b02687c6677: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:49,750 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  44%|████▍     | 58/131 [00:05<00:04, 17.49it/s]2026-04-14 11:53:49,913 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,029 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,030 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,032 | WARNING | Classification failed for chunk 0bc9942864dad29ae46db000bab660f6399f38e0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:50,034 | INFO | Classification pool progress: 60/131 chunks completed.
Classifying retrieved chunks (40 workers):  46%|████▌     | 60/131 [00:05<00:05, 13.57it/s]2026-04-14 11:53:50,057 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,059 | WARNING | Classification failed for chunk 7954d1d15081ddef40a6a7a7e2bad3eb638fc877: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:50,076 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,078 | WARNING | Classification failed for chunk 1f29b71ea9cc4a50d7b50efd83ff0d0144520b6e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:50,121 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:53:50,123 | WARNING | Classification failed for chunk 2ecdfd7274caa51eaa45b4d3652d4be3b79d13a1: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:53:50,140 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Running pipeline for: Elmos

Extracting pages: Elmos: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
Chunking clean pages: 100%|██████████| 64/64 [00:00<00:00, 1904.08it/s]
Batches: 100%|██████████| 6/6 [00:01<00:00,  5.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.52it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 165.26it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 159.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 157.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.96it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 175.53it/s]<00:00, 69.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 173.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 169.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 163.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 169.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 156.86it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 193.79it/s]0<00:00, 71.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 179.76it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 149.24it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 71.16it/s]
2026-04-14 11:54:28,735 | INFO | Starting classification pool for 88 retrieved chunks with up to 40 worker threads.
2026-04-14 11:54:28,752 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:54:28,754 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:54:28,754 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:54:28,754 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:54:28,754 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:54:28,754 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:54:28,755 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:54:28,755 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:54:28,755 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:54:28,756 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:54:28,756 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:54:28,757 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:54:28,759 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:54:28,761 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:54:28,761 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:54:28,761 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:54:28,762 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:54:28,765 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:54:28,767 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:54:28,769 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:54:28,771 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:54:28,772 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:54:28,772 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:54:28,773 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:54:28,773 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:54:28,774 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:54:28,774 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:54:28,776 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:54:28,777 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:54:28,777 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:54:28,783 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:54:28,783 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:54:28,786 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:54:28,786 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:54:28,787 | INFO | Submitted 88 classification tasks to the worker pool.
2026-04-14 11:54:28,789 | INFO | Initialized OpenAI client in worker thread classifier_35
Classifying retrieved chunks (40 workers):   0%|          | 0/88 [00:00<?, ?it/s]2026-04-14 11:54:28,789 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:54:28,789 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:54:28,790 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:54:28,791 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:54:28,793 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:54:29,880 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:29,881 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/88 [00:01<01:33,  1.08s/it]2026-04-14 11:54:29,909 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:29,942 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:29,952 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:29,995 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,017 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   3%|▎         | 3/88 [00:01<00:27,  3.05it/s]2026-04-14 11:54:30,035 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,038 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,046 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,071 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,076 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,086 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,095 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,102 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,106 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,160 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,164 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,217 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,219 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,230 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,254 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,258 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   9%|▉         | 8/88 [00:01<00:09,  8.03it/s]2026-04-14 11:54:30,259 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,265 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,400 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,685 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,689 | INFO | Classification pool progress: 10/88 chunks completed.
Classifying retrieved chunks (40 workers):  11%|█▏        | 10/88 [00:01<00:11,  6.60it/s]2026-04-14 11:54:30,925 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,926 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,928 | WARNING | Classification failed for chunk 6069728b2eb733a067c3844ff6682a3fb4be1af3: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:30,980 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,982 | WARNING | Classification failed for chunk b12e568a2ea49948511b434ede6304d0922f9008: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  14%|█▎        | 12/88 [00:02<00:11,  6.66it/s]2026-04-14 11:54:30,983 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,986 | WARNING | Classification failed for chunk 2c711d25c1c23445ecfc8b3d74be835478e1d341: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:30,987 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,989 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:30,991 | WARNING | Classification failed for chunk d3d4e3cb51159afdda3ed92f129bd33733e41c28: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,016 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,020 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,052 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,066 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,067 | WARNING | Classification failed for chunk 5f0f1acb13f03f01fe947d4b33cfe4047fe100eb: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,097 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,163 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,189 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,191 | WARNING | Classification failed for chunk 76c031241d64f6bda00ff1adab652ce41175269d: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  20%|██        | 18/88 [00:02<00:05, 11.67it/s]2026-04-14 11:54:31,199 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,221 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,223 | WARNING | Classification failed for chunk 975ea5140d1cb16695f5c0c7ae1d11e60511efd0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,225 | INFO | Classification pool progress: 20/88 chunks completed.
2026-04-14 11:54:31,266 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,268 | WARNING | Classification failed for chunk de6a546ca235bbf26c0461d3fd8306b2c16cfcf3: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,275 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,289 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,291 | WARNING | Classification failed for chunk 924eab4cb22086f49a10e1697f5949f164cf46cc: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,299 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,299 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,301 | WARNING | Classification failed for chunk f814950f396c2e1edab9624428fae0de78791ab0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,302 | WARNING | Classification failed for chunk c6c489454be9f095c566bba8ff0b3ac14476d32a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  26%|██▌       | 23/88 [00:02<00:03, 16.59it/s]2026-04-14 11:54:31,313 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,315 | WARNING | Classification failed for chunk 6cd1059391625b050ae9fcc412dc75acdd57d3cb: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,334 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,451 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,452 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,517 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,518 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  30%|██▉       | 26/88 [00:02<00:03, 15.66it/s]2026-04-14 11:54:31,519 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,535 | WARNING | Classification failed for chunk 569beba711e035aff0c93c6c0caff9a2f8b731e6: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:31,702 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,723 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,842 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,844 | WARNING | Classification failed for chunk 789841b93a287f153018d8f2b1f4367bed9409be: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  33%|███▎      | 29/88 [00:03<00:04, 13.29it/s]2026-04-14 11:54:31,973 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,974 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:31,980 | INFO | Classification pool progress: 30/88 chunks completed.
Classifying retrieved chunks (40 workers):  35%|███▌      | 31/88 [00:03<00:04, 13.56it/s]2026-04-14 11:54:32,038 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,054 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,056 | WARNING | Classification failed for chunk 9aad5feda39f30c2925628891c7759bd728ea55a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,084 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,086 | WARNING | Classification failed for chunk bf960c10977594d4e8a938371348c0e8dbd80959: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  38%|███▊      | 33/88 [00:03<00:03, 14.47it/s]2026-04-14 11:54:32,088 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,153 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,155 | WARNING | Classification failed for chunk c05ddd86fd10631525929ce0ac51edc0b3d29ec9: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,163 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,185 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,294 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,403 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,494 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,497 | WARNING | Classification failed for chunk 7ef529ed000b4df93f2af7f818479fd7c45e776b: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,498 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  40%|███▉      | 35/88 [00:03<00:05,  9.77it/s]2026-04-14 11:54:32,502 | WARNING | Classification failed for chunk d47d97632ba0d8f20773d208fae2c04e722c25a6: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,511 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,511 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,519 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,579 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,625 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  43%|████▎     | 38/88 [00:03<00:04, 12.19it/s]2026-04-14 11:54:32,652 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,720 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,723 | WARNING | Classification failed for chunk eec2fc9c129716f54f014f66199b9c2bf88ff442: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,731 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,789 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,804 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:32,806 | WARNING | Classification failed for chunk 7ba81baff20661ce9a31c08e5b9756307f7fd682: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:32,807 | INFO | Classification pool progress: 40/88 chunks completed.
Classifying retrieved chunks (40 workers):  45%|████▌     | 40/88 [00:03<00:04, 11.91it/s]2026-04-14 11:54:32,828 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Running pipeline for: Infineon

Extracting pages: Infineon: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]
Chunking clean pages: 100%|██████████| 192/192 [00:00<00:00, 2509.45it/s]
Batches: 100%|██████████| 15/15 [00:02<00:00,  6.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.53it/s]0<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 69.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.43it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.50it/s]<00:00, 55.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 16.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.92it/s]00<00:00, 31.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.11it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 39.75it/s]00<00:00, 28.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 38.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 88.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.11it/s]0<00:00, 27.44it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 79.65it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 31.21it/s]
2026-04-14 11:54:51,026 | INFO | Starting classification pool for 123 retrieved chunks with up to 40 worker threads.
2026-04-14 11:54:51,040 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:54:51,043 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:54:51,043 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:54:51,043 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:54:51,043 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:54:51,044 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:54:51,045 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:54:51,046 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:54:51,057 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:54:51,059 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:54:51,059 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:54:51,059 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:54:51,060 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:54:51,065 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:54:51,068 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:54:51,069 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:54:51,070 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:54:51,070 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:54:51,070 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:54:51,075 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:54:51,075 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:54:51,076 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:54:51,080 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:54:51,084 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:54:51,084 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:54:51,084 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:54:51,085 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:54:51,086 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:54:51,091 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:54:51,092 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:54:51,094 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:54:51,094 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:54:51,095 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:54:51,099 | INFO | Submitted 123 classification tasks to the worker pool.
2026-04-14 11:54:51,099 | INFO | Initialized OpenAI client in worker thread classifier_34
Classifying retrieved chunks (40 workers):   0%|          | 0/123 [00:00<?, ?it/s]2026-04-14 11:54:51,100 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:54:51,101 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:54:51,102 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:54:51,102 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:54:51,103 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:54:51,106 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:54:52,101 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/123 [00:00<01:59,  1.02it/s]2026-04-14 11:54:52,167 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,211 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   2%|▏         | 3/123 [00:01<00:35,  3.40it/s]2026-04-14 11:54:52,238 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,250 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,314 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   5%|▍         | 6/123 [00:01<00:15,  7.44it/s]2026-04-14 11:54:52,426 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,426 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,427 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   7%|▋         | 8/123 [00:01<00:12,  9.40it/s]2026-04-14 11:54:52,427 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,428 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,428 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,442 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,444 | INFO | Classification pool progress: 10/123 chunks completed.
2026-04-14 11:54:52,486 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,527 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,537 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  11%|█▏        | 14/123 [00:01<00:05, 19.27it/s]2026-04-14 11:54:52,542 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,548 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,580 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,624 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,683 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  15%|█▌        | 19/123 [00:01<00:04, 23.56it/s]2026-04-14 11:54:52,834 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,838 | INFO | Classification pool progress: 20/123 chunks completed.
2026-04-14 11:54:52,945 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,947 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,948 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:52,949 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  19%|█▊        | 23/123 [00:01<00:05, 19.73it/s]2026-04-14 11:54:53,029 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,050 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  21%|██        | 26/123 [00:01<00:04, 21.49it/s]2026-04-14 11:54:53,090 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,092 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,130 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,169 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,208 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,211 | INFO | Classification pool progress: 30/123 chunks completed.
Classifying retrieved chunks (40 workers):  24%|██▍       | 30/123 [00:02<00:04, 22.94it/s]2026-04-14 11:54:53,228 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,310 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,333 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,473 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  27%|██▋       | 33/123 [00:02<00:04, 18.07it/s]2026-04-14 11:54:53,486 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,519 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,523 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 500 Internal Server Error"
2026-04-14 11:54:53,527 | INFO | Retrying request to /responses in 0.490392 seconds
2026-04-14 11:54:53,554 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,554 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,608 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,609 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  31%|███       | 38/123 [00:02<00:03, 22.51it/s]2026-04-14 11:54:53,622 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,623 | WARNING | Classification failed for chunk bcf0d5a3ac7da60d4ea73af286d322171f8d78ca: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:53,637 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,639 | INFO | Classification pool progress: 40/123 chunks completed.
2026-04-14 11:54:53,689 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,769 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,805 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  33%|███▎      | 41/123 [00:02<00:04, 20.16it/s]2026-04-14 11:54:53,810 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,813 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,840 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:53,845 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,069 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  36%|███▌      | 44/123 [00:02<00:04, 16.74it/s]2026-04-14 11:54:54,148 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,187 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,279 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  37%|███▋      | 46/123 [00:03<00:05, 14.55it/s]2026-04-14 11:54:54,364 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,395 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  39%|███▉      | 48/123 [00:03<00:04, 15.08it/s]2026-04-14 11:54:54,399 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,519 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,520 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,522 | WARNING | Classification failed for chunk f0ea1e23adbbaeb1a40d4b76af7a4b56d94d547a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:54,526 | INFO | Classification pool progress: 50/123 chunks completed.
Classifying retrieved chunks (40 workers):  41%|████      | 50/123 [00:03<00:04, 15.22it/s]2026-04-14 11:54:54,572 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,574 | WARNING | Classification failed for chunk 46f50599699970d28ee5efb718c4df7181874ae7: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:54,577 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,628 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  42%|████▏     | 52/123 [00:03<00:04, 16.01it/s]2026-04-14 11:54:54,705 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,746 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,774 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,775 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,812 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,837 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,839 | WARNING | Classification failed for chunk 2b738bf482fc9ab9fcd02b5970808105b4431ce4: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  44%|████▍     | 54/123 [00:03<00:05, 13.58it/s]2026-04-14 11:54:54,861 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,884 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,901 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,903 | WARNING | Classification failed for chunk df35b77aa5069e137197d97162c6302f56d3a3ab: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:54,948 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:54,949 | WARNING | Classification failed for chunk 6d34ebed618240417a5560252669ff4ead1bd22d: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  46%|████▋     | 57/123 [00:03<00:03, 16.63it/s]2026-04-14 11:54:55,037 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  48%|████▊     | 59/123 [00:04<00:04, 13.55it/s]2026-04-14 11:54:55,181 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,182 | WARNING | Classification failed for chunk 3927b7e1f25d201bb054bccc1b13684951c1a885: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:55,184 | INFO | Classification pool progress: 60/123 chunks completed.
2026-04-14 11:54:55,211 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,394 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,396 | WARNING | Classification failed for chunk 40e562e94fcb34b1a4e3f55f93bedcdaa1d9833c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  50%|████▉     | 61/123 [00:04<00:05, 11.97it/s]2026-04-14 11:54:55,447 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,463 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,563 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,564 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,564 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,565 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  51%|█████     | 63/123 [00:04<00:05, 11.88it/s]2026-04-14 11:54:55,567 | WARNING | Classification failed for chunk 546a02a32d4ed06be0b20d982d97f0be5154cbb6: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:54:55,570 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,646 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,665 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,689 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,855 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,896 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:54:55,898 | WARNING | Classification failed for chunk d1a88b73834d4cea1f177c4be400270f6f569b3e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.

Running pipeline for: Intel

Extracting pages: Intel: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
Chunking clean pages: 100%|██████████| 172/172 [00:00<00:00, 2744.76it/s]
Batches: 100%|██████████| 13/13 [00:01<00:00,  9.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.50it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 183.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.79it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 207.85it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 190.19it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 192.16it/s]<00:00, 77.60it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 203.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 209.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 203.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 207.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 154.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 168.41it/s]0<00:00, 82.41it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.33it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 181.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 188.08it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.78it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 54.35it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 74.32it/s]
2026-04-14 11:55:25,143 | INFO | Starting classification pool for 125 retrieved chunks with up to 40 worker threads.
2026-04-14 11:55:25,151 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:55:25,153 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:55:25,153 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:55:25,154 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:55:25,154 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:55:25,155 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:55:25,156 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:55:25,157 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:55:25,158 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:55:25,158 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:55:25,160 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:55:25,161 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:55:25,161 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:55:25,163 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:55:25,166 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:55:25,172 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:55:25,172 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:55:25,173 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:55:25,175 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:55:25,175 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:55:25,176 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:55:25,177 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:55:25,179 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:55:25,180 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:55:25,181 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:55:25,182 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:55:25,183 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:55:25,183 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:55:25,184 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:55:25,188 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:55:25,188 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:55:25,189 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:55:25,189 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:55:25,190 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:55:25,191 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:55:25,191 | INFO | Submitted 125 classification tasks to the worker pool.
2026-04-14 11:55:25,193 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:55:25,193 | INFO | Initialized OpenAI client in worker thread classifier_35
Classifying retrieved chunks (40 workers):   0%|          | 0/125 [00:00<?, ?it/s]2026-04-14 11:55:25,194 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:55:25,194 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:55:25,196 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:55:26,166 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/125 [00:00<01:58,  1.04it/s]2026-04-14 11:55:26,176 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,190 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,310 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,330 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,367 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,385 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,502 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,502 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   2%|▏         | 3/125 [00:01<00:45,  2.68it/s]2026-04-14 11:55:26,503 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,504 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,505 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,518 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,521 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,525 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:26,631 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,199 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,202 | WARNING | Classification failed for chunk c5fa477fac569421994a78822cca33a98b977157: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):   6%|▋         | 8/125 [00:01<00:23,  4.92it/s]2026-04-14 11:55:27,221 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,232 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,236 | INFO | Classification pool progress: 10/125 chunks completed.
2026-04-14 11:55:27,307 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,308 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   9%|▉         | 11/125 [00:02<00:15,  7.18it/s]2026-04-14 11:55:27,370 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,372 | WARNING | Classification failed for chunk 9a713a825dc59c24a7e537aa04aecd2e743b0466: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,412 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  11%|█         | 14/125 [00:02<00:11,  9.79it/s]2026-04-14 11:55:27,434 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,435 | WARNING | Classification failed for chunk aa432e7af35e73afa6dbfdbc3aa60659cf300c42: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,554 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,554 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,555 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  13%|█▎        | 16/125 [00:02<00:10, 10.55it/s]2026-04-14 11:55:27,569 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,573 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,647 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,649 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,649 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,650 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,652 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,653 | WARNING | Classification failed for chunk 77dd396195bf14f9c7572679c280225a0ce0734c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,655 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,655 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,681 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,685 | INFO | Classification pool progress: 20/125 chunks completed.
Classifying retrieved chunks (40 workers):  16%|█▌        | 20/125 [00:02<00:07, 14.33it/s]2026-04-14 11:55:27,686 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,691 | WARNING | Classification failed for chunk 3cf65b50f523e581b47755c2d67592f8b78e98d7: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,699 | WARNING | Classification failed for chunk 0359287d364b46bf823c9db88838ef3d02d53b57: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,702 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,704 | WARNING | Classification failed for chunk 7c356ed0143360d60b179c8046a1ff05a5ccf6bc: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,711 | WARNING | Classification failed for chunk c2a2430d12877cbb43ef84e0cc6e9ad0325d3b21: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,716 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,763 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,764 | WARNING | Classification failed for chunk 8c40dde397f90138e2806be9cad03972cba58b1c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:27,785 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,787 | INFO | Classification pool progress: 30/125 chunks completed.
2026-04-14 11:55:27,964 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:27,964 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,075 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,264 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,384 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,405 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,439 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  25%|██▍       | 31/125 [00:03<00:06, 14.66it/s]2026-04-14 11:55:28,503 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,597 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,597 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  26%|██▋       | 33/125 [00:03<00:06, 14.33it/s]2026-04-14 11:55:28,598 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,644 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,765 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,781 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,783 | WARNING | Classification failed for chunk 6f178865d122e94450910949e27d2b06ff5fcdf3: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  29%|██▉       | 36/125 [00:03<00:06, 14.75it/s]2026-04-14 11:55:28,886 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,888 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  30%|███       | 38/125 [00:03<00:05, 15.30it/s]2026-04-14 11:55:28,894 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,898 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,909 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,961 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:28,977 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,000 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,124 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,125 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,128 | INFO | Classification pool progress: 40/125 chunks completed.
Classifying retrieved chunks (40 workers):  32%|███▏      | 40/125 [00:03<00:06, 13.11it/s]2026-04-14 11:55:29,178 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,239 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,242 | WARNING | Classification failed for chunk 93a4489feb8582fa9e863dd7cfd0118fd741795a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  34%|███▍      | 43/125 [00:04<00:05, 15.50it/s]2026-04-14 11:55:29,283 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,286 | WARNING | Classification failed for chunk 4571173717e48091afc1923eed1328e181757257: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:29,309 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,313 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,315 | WARNING | Classification failed for chunk eadb11d4977ce953b3038fd2edf337056ec6ab64: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:29,361 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,363 | WARNING | Classification failed for chunk 3e3d0c2df46ff25a23ddd50da3d09c5b2008a6d5: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  37%|███▋      | 46/125 [00:04<00:04, 17.48it/s]2026-04-14 11:55:29,650 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,653 | WARNING | Classification failed for chunk 0d45c49def8d4fb188134f63ae86788f479fbdfe: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:29,702 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,746 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,817 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:29,820 | WARNING | Classification failed for chunk 06014c6bbe9f6813b840ff2faf0d59930c93b686: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  39%|███▉      | 49/125 [00:04<00:06, 11.62it/s]2026-04-14 11:55:29,907 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,018 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,022 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,056 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,058 | WARNING | Classification failed for chunk 181a62ad25c126a4070fcb7fb3bad76b745d43ec: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:55:30,060 | INFO | Classification pool progress: 50/125 chunks completed.
2026-04-14 11:55:30,174 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  41%|████      | 51/125 [00:04<00:07,  9.38it/s]2026-04-14 11:55:30,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,176 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:55:30,181 | WARNING | Classification failed for chunk 467ecb7bdfd90876109b82a0d9f3d9980ee58d75: Classification failed after 2 attempts: 'secondary_category' must be a string or null.

Running pipeline for: MediaTek

Extracting pages: MediaTek: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
Chunking clean pages: 100%|██████████| 285/285 [00:00<00:00, 3845.11it/s]
Batches: 100%|██████████| 15/15 [00:01<00:00,  8.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 27.61it/s]0<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 28.40it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 152.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]0<00:00, 35.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 152.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.53it/s]<00:00, 33.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 190.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 157.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 181.55it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 29.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 200.57it/s]0<00:00, 43.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 159.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 148.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 25.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.07it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.46it/s]0<00:00, 47.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 49.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.50it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 45.29it/s]
2026-04-14 11:55:59,031 | INFO | Starting classification pool for 77 retrieved chunks with up to 40 worker threads.
2026-04-14 11:55:59,044 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:55:59,045 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:55:59,045 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:55:59,046 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:55:59,046 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:55:59,047 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:55:59,047 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:55:59,047 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:55:59,047 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:55:59,050 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:55:59,052 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:55:59,052 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:55:59,052 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:55:59,053 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:55:59,053 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:55:59,056 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:55:59,058 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:55:59,058 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:55:59,060 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:55:59,062 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:55:59,062 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:55:59,064 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:55:59,065 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:55:59,065 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:55:59,071 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:55:59,072 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:55:59,072 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:55:59,074 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:55:59,074 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:55:59,075 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:55:59,076 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:55:59,076 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:55:59,078 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:55:59,079 | INFO | Submitted 77 classification tasks to the worker pool.
2026-04-14 11:55:59,079 | INFO | Initialized OpenAI client in worker thread classifier_33
Classifying retrieved chunks (40 workers):   0%|          | 0/77 [00:00<?, ?it/s]2026-04-14 11:55:59,080 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:55:59,082 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:55:59,084 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:55:59,085 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:55:59,086 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:55:59,086 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:56:00,063 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,069 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,084 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,090 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,090 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|▏         | 1/77 [00:00<01:15,  1.01it/s]2026-04-14 11:56:00,120 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,120 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,150 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,197 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,224 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,244 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,255 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,267 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   4%|▍         | 3/77 [00:01<00:23,  3.10it/s]2026-04-14 11:56:00,271 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,277 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,306 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,331 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,355 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,389 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,395 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   9%|▉         | 7/77 [00:01<00:08,  8.00it/s]2026-04-14 11:56:00,416 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,581 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,581 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,590 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,596 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  12%|█▏        | 9/77 [00:01<00:07,  8.54it/s]2026-04-14 11:56:00,761 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,765 | INFO | Classification pool progress: 10/77 chunks completed.
2026-04-14 11:56:00,893 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,895 | WARNING | Classification failed for chunk 175113b7a9326822e364567157d5c325a16dce9a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  14%|█▍        | 11/77 [00:01<00:08,  7.86it/s]2026-04-14 11:56:00,917 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:00,919 | WARNING | Classification failed for chunk 0c855bf637e2b62c110cbb6e4cd00a5ce3844251: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,107 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,108 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,109 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,110 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,113 | WARNING | Classification failed for chunk b6d8eb30e034d41c78aca17345108ebe052f7441: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,113 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  17%|█▋        | 13/77 [00:02<00:07,  8.17it/s]2026-04-14 11:56:01,116 | WARNING | Classification failed for chunk 0ed2490a20e765996cae2734b1257c510bf7a139: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,117 | WARNING | Classification failed for chunk 0c4b924cbca7e674d9691718241d894afd8bec53: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,118 | WARNING | Classification failed for chunk 594e4df8be8df2c09264ddeb1657f3325cf8f2ba: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,134 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,138 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,180 | WARNING | Classification failed for chunk 484c48ca7268979ae50eb4d4ed0595371ac9b50e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,210 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,261 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,262 | WARNING | Classification failed for chunk 206b2f8eb4d3be16db700b96dabc8c8f55527512: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,263 | INFO | Classification pool progress: 20/77 chunks completed.
Classifying retrieved chunks (40 workers):  26%|██▌       | 20/77 [00:02<00:03, 16.58it/s]2026-04-14 11:56:01,306 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,306 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,309 | WARNING | Classification failed for chunk fd9ad21f97426a450e907063bd0053de0580a2a1: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,309 | WARNING | Classification failed for chunk 2d9355a31cdcbe3cc6266d6b60a31bea51a0b83f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,329 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,380 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,385 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,387 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,388 | WARNING | Classification failed for chunk 18439309a9b2e7a9e1a37e98414d5e8ca51e7e34: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  30%|██▉       | 23/77 [00:02<00:02, 18.11it/s]2026-04-14 11:56:01,436 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,438 | WARNING | Classification failed for chunk f7e7cde9f4637d732540dfc42156cb23e9d1e5bb: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,468 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,472 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,473 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,474 | WARNING | Classification failed for chunk 62416ee80f58a6f6610eaff88ced07ea7c0bfb9b: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,475 | WARNING | Classification failed for chunk 55103104442916d72e67eec95c0d9aab64fff676: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,488 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,492 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  36%|███▋      | 28/77 [00:02<00:02, 23.86it/s]2026-04-14 11:56:01,513 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,515 | INFO | Classification pool progress: 30/77 chunks completed.
2026-04-14 11:56:01,625 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,626 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,626 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,638 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  42%|████▏     | 32/77 [00:02<00:01, 24.88it/s]2026-04-14 11:56:01,663 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,665 | WARNING | Classification failed for chunk eaf413e863c7066cc57b7fde161e63e62fad58e2: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:01,684 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,763 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,827 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,880 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,887 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:01,937 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  45%|████▌     | 35/77 [00:02<00:02, 18.16it/s]2026-04-14 11:56:01,960 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,032 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,157 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,206 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,299 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,318 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,326 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,333 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,353 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,357 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,358 | WARNING | Classification failed for chunk cb885c7aec8608290483e6291bd5c9f37c4b0467: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  49%|████▉     | 38/77 [00:03<00:03, 12.95it/s]2026-04-14 11:56:02,366 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,378 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,381 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,383 | WARNING | Classification failed for chunk 829659f541ae2806c4114308984a824cd9c7edcd: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:02,410 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,411 | WARNING | Classification failed for chunk 8067c93c87b3bd03f525e9c97a5e67cff03ae004: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:02,412 | INFO | Classification pool progress: 40/77 chunks completed.
2026-04-14 11:56:02,414 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,415 | WARNING | Classification failed for chunk 0ae69901b1036d2c43db388735e27c449848f738: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:02,433 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,458 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,458 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,460 | WARNING | Classification failed for chunk 70620d38f2566d1113b93dc4a81739d96c2431ec: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:02,461 | WARNING | Classification failed for chunk 6e8c4294a6368579f5044d0252b3853c148a34ab: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  56%|█████▌    | 43/77 [00:03<00:01, 18.05it/s]2026-04-14 11:56:02,473 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,679 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,679 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:02,679 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Running pipeline for: Micron

Extracting pages: Micron: 100%|██████████| 1/1 [00:00<00:00,  2.61it/s]
Chunking clean pages: 100%|██████████| 119/119 [00:00<00:00, 2503.41it/s]
Batches: 100%|██████████| 10/10 [00:01<00:00,  8.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.72it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.02it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 183.82it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 201.13it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 185.74it/s]<00:00, 73.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.48it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 166.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 95.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 171.93it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 212.59it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.09it/s]0<00:00, 76.24it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 180.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 198.81it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 162.97it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.99it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 175.25it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 74.66it/s]
2026-04-14 11:56:11,194 | INFO | Starting classification pool for 92 retrieved chunks with up to 40 worker threads.
2026-04-14 11:56:11,202 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:56:11,203 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:56:11,203 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:56:11,203 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:56:11,204 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:56:11,204 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:56:11,205 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:56:11,206 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:56:11,206 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:56:11,207 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:56:11,207 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:56:11,207 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:56:11,213 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:56:11,213 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:56:11,215 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:56:11,215 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:56:11,215 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:56:11,215 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:56:11,215 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:56:11,218 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:56:11,219 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:56:11,219 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:56:11,222 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:56:11,223 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:56:11,224 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:56:11,224 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:56:11,226 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:56:11,226 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:56:11,227 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:56:11,230 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:56:11,233 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:56:11,234 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:56:11,235 | INFO | Submitted 92 classification tasks to the worker pool.
2026-04-14 11:56:11,235 | INFO | Initialized OpenAI client in worker thread classifier_32
Classifying retrieved chunks (40 workers):   0%|          | 0/92 [00:00<?, ?it/s]2026-04-14 11:56:11,236 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:56:11,236 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:56:11,236 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:56:11,237 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:56:11,238 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:56:11,240 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:56:11,240 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:56:12,179 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,232 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,330 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/92 [00:01<01:37,  1.07s/it]2026-04-14 11:56:12,339 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,359 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,364 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,368 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,389 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,390 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,439 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   3%|▎         | 3/92 [00:01<00:28,  3.13it/s]2026-04-14 11:56:12,475 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,517 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,638 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,638 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   5%|▌         | 5/92 [00:01<00:17,  4.85it/s]2026-04-14 11:56:12,639 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,640 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,709 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,717 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,722 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,895 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,899 | INFO | Classification pool progress: 10/92 chunks completed.
Classifying retrieved chunks (40 workers):  11%|█         | 10/92 [00:01<00:08,  9.43it/s]2026-04-14 11:56:12,907 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:12,922 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,036 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,046 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,048 | WARNING | Classification failed for chunk 87e0570318ac9252d436e5059219c26ee0138e47: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  13%|█▎        | 12/92 [00:01<00:07, 10.23it/s]2026-04-14 11:56:13,061 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,063 | WARNING | Classification failed for chunk af218a25e2947dc6dc91625868e91b30dc494a44: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:13,216 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,292 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,293 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,297 | WARNING | Classification failed for chunk e274a7dba1d44f711f038d885320a8b77ae6aacf: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  15%|█▌        | 14/92 [00:02<00:08,  9.51it/s]2026-04-14 11:56:13,334 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,336 | WARNING | Classification failed for chunk 4f9725608bd102a4ff9bd53a962286d5427b2881: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:13,393 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,436 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,440 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,454 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  17%|█▋        | 16/92 [00:02<00:07, 10.23it/s]2026-04-14 11:56:13,486 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,543 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,545 | WARNING | Classification failed for chunk 5e6fd0681b88d0433cc47c479bd3a5999cb3ba12: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:13,550 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,576 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,577 | WARNING | Classification failed for chunk 1fb2b7691a812a7af92aecc46ec82a6eb3b24564: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  21%|██        | 19/92 [00:02<00:05, 13.15it/s]2026-04-14 11:56:13,688 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,689 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,689 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,690 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,693 | INFO | Classification pool progress: 20/92 chunks completed.
Classifying retrieved chunks (40 workers):  23%|██▎       | 21/92 [00:02<00:05, 13.93it/s]2026-04-14 11:56:13,912 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  25%|██▌       | 23/92 [00:02<00:05, 12.20it/s]2026-04-14 11:56:13,929 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,941 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:13,943 | WARNING | Classification failed for chunk ed535978be7508caf897267d8f3f0ee1c27a3a21: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:14,034 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  28%|██▊       | 26/92 [00:02<00:04, 15.01it/s]2026-04-14 11:56:14,213 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,214 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,250 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,251 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,252 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,258 | WARNING | Classification failed for chunk bc06a61a4f452db6f67ada7cbc6b844d328a5303: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  30%|███       | 28/92 [00:03<00:05, 12.78it/s]2026-04-14 11:56:14,268 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,270 | WARNING | Classification failed for chunk 701a0537c9ed11c3010f33334a109237548f32b9: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:14,537 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,540 | WARNING | Classification failed for chunk d039d36f9f6dc9f849053d1cf0f3926feaa8f2e0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:14,542 | INFO | Classification pool progress: 30/92 chunks completed.
Classifying retrieved chunks (40 workers):  33%|███▎      | 30/92 [00:03<00:05, 10.47it/s]2026-04-14 11:56:14,541 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,546 | WARNING | Classification failed for chunk 70469df0dfa05084cc4a329c88fea0fa574011fe: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:14,612 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,625 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,627 | WARNING | Classification failed for chunk c61a2b681e737b4c76bf082b173c76af83af9201: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:14,739 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,739 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,740 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  37%|███▋      | 34/92 [00:03<00:04, 13.15it/s]2026-04-14 11:56:14,847 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,876 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:14,879 | WARNING | Classification failed for chunk a05d1b0034c75f4fac8a295f6d0e15bd23b7c384: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  39%|███▉      | 36/92 [00:03<00:04, 13.57it/s]2026-04-14 11:56:14,958 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,005 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,006 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,057 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,064 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,065 | WARNING | Classification failed for chunk 12602065ba30a43c012a480b429786cc0b4d4fea: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  41%|████▏     | 38/92 [00:03<00:04, 12.71it/s]2026-04-14 11:56:15,264 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,265 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,266 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,267 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,272 | WARNING | Classification failed for chunk 4608fbae978e4b3eb7a4d364bcbab596f3e5d74f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:15,275 | INFO | Classification pool progress: 40/92 chunks completed.
Classifying retrieved chunks (40 workers):  43%|████▎     | 40/92 [00:04<00:04, 11.61it/s]2026-04-14 11:56:15,299 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,410 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,411 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  47%|████▋     | 43/92 [00:04<00:03, 14.00it/s]2026-04-14 11:56:15,463 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,467 | WARNING | Classification failed for chunk b441d5462cd8223d6bb25ca7c2d3d2fb256d82df: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:15,487 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,521 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,523 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,524 | WARNING | Classification failed for chunk 288eb69ddb40c6bfec2abf75af29ef27e9e53a36: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  50%|█████     | 46/92 [00:04<00:02, 16.76it/s]2026-04-14 11:56:15,676 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,787 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,787 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,789 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:15,793 | WARNING | Classification failed for chunk 1e422cc7ae1a1fdb5650eae0c955d3d515f55504: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:15,792 | WARNING | Classification failed for chunk 35f518be623fccaf2d341566f3f416b9e15e6441: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  52%|█████▏    | 48/92 [00:04<00:03, 12.86it/s]2026-04-14 11:56:15,799 | INFO | Classification pool progress: 50/92 chunks completed.

Running pipeline for: NXP

Extracting pages: NXP: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
Chunking clean pages: 100%|██████████| 142/142 [00:00<00:00, 2022.22it/s]
Batches: 100%|██████████| 14/14 [00:01<00:00,  9.20it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.83it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 151.50it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 202.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 201.74it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 178.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 185.76it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 165.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 212.05it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 203.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 204.11it/s]<00:00, 83.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 182.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 203.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 203.63it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 186.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 157.56it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 189.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 199.76it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 185.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 210.58it/s]0<00:00, 85.45it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 202.51it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 158.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 189.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 194.67it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 85.16it/s]
2026-04-14 11:56:29,451 | INFO | Starting classification pool for 113 retrieved chunks with up to 40 worker threads.
2026-04-14 11:56:29,459 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:56:29,460 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:56:29,460 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:56:29,460 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:56:29,461 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:56:29,461 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:56:29,462 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:56:29,464 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:56:29,465 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:56:29,467 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:56:29,467 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:56:29,470 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:56:29,471 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:56:29,471 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:56:29,471 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:56:29,472 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:56:29,474 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:56:29,475 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:56:29,477 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:56:29,478 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:56:29,478 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:56:29,479 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:56:29,480 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:56:29,483 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:56:29,483 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:56:29,484 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:56:29,484 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:56:29,485 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:56:29,485 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:56:29,487 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:56:29,489 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:56:29,491 | INFO | Submitted 113 classification tasks to the worker pool.
2026-04-14 11:56:29,491 | INFO | Initialized OpenAI client in worker thread classifier_33
Classifying retrieved chunks (40 workers):   0%|          | 0/113 [00:00<?, ?it/s]2026-04-14 11:56:29,491 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:56:29,491 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:56:29,493 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:56:29,494 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:56:29,494 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:56:29,495 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:56:29,496 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:56:29,496 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:56:30,462 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,553 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,645 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,651 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,654 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/113 [00:01<02:08,  1.15s/it]2026-04-14 11:56:30,661 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,723 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,728 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,759 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   4%|▍         | 5/113 [00:01<00:20,  5.18it/s]2026-04-14 11:56:30,785 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,792 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,797 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,832 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,868 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   7%|▋         | 8/113 [00:01<00:12,  8.44it/s]2026-04-14 11:56:30,986 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,987 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,987 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,987 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:30,991 | INFO | Classification pool progress: 10/113 chunks completed.
Classifying retrieved chunks (40 workers):  10%|▉         | 11/113 [00:01<00:08, 11.53it/s]2026-04-14 11:56:31,067 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,129 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  12%|█▏        | 14/113 [00:01<00:07, 13.94it/s]2026-04-14 11:56:31,160 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,238 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,381 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,535 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,537 | WARNING | Classification failed for chunk 109e2a986489f02e642b722d19b4847fafc7a922: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  15%|█▌        | 17/113 [00:02<00:08, 10.67it/s]2026-04-14 11:56:31,586 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,588 | WARNING | Classification failed for chunk 94d8a69e7c0b38e59d0628dd337dd55bd798b751: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:31,675 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,677 | WARNING | Classification failed for chunk a5608e8e3c0cd750b35a37b150eaa90f2c924b45: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  17%|█▋        | 19/113 [00:02<00:08, 11.36it/s]2026-04-14 11:56:31,725 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,728 | INFO | Classification pool progress: 20/113 chunks completed.
2026-04-14 11:56:31,765 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,863 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,898 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,900 | WARNING | Classification failed for chunk 860852c7d5f7ad48d29b15591819dc8330cf396f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  19%|█▉        | 22/113 [00:02<00:07, 12.00it/s]2026-04-14 11:56:31,920 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:31,930 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,038 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,039 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,039 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,040 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,041 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  21%|██        | 24/113 [00:02<00:07, 12.36it/s]2026-04-14 11:56:32,046 | WARNING | Classification failed for chunk 7af0c63a4f9cf491d5b2b5ace374c10419fc64a1: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:32,056 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,062 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,096 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,165 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,169 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,195 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  25%|██▍       | 28/113 [00:02<00:05, 15.92it/s]2026-04-14 11:56:32,199 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,209 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,217 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,224 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,238 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,275 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,277 | INFO | Classification pool progress: 30/113 chunks completed.
2026-04-14 11:56:32,316 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,317 | WARNING | Classification failed for chunk 547aced6cda8f5cdc7f82ace15a5c79c41be83d5: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  27%|██▋       | 31/113 [00:02<00:04, 17.93it/s]2026-04-14 11:56:32,366 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,405 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,561 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,564 | WARNING | Classification failed for chunk dd6cd6fa96908c2d29afe79192bc3fe742e729db: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:32,742 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,744 | WARNING | Classification failed for chunk bceabe5369140c2028e1af96ab3fc578af867d3f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:32,860 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,875 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,885 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,915 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  30%|███       | 34/113 [00:03<00:07, 10.02it/s]2026-04-14 11:56:32,941 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,960 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:32,962 | WARNING | Classification failed for chunk 4301366ec3b70d41efe6a7ebf5e729ff1dc2250b: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:32,967 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,089 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,090 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  32%|███▏      | 36/113 [00:03<00:07, 10.31it/s]2026-04-14 11:56:33,141 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,164 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,166 | WARNING | Classification failed for chunk 794ad60b352f186d47a37a97dca20f7313f08174: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,168 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,198 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,199 | WARNING | Classification failed for chunk c9dc589ca8f8a1570e53061f25529518323cb814: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  35%|███▍      | 39/113 [00:03<00:05, 12.97it/s]2026-04-14 11:56:33,208 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,278 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,280 | WARNING | Classification failed for chunk 8105d0c65313039e576eed99d4fec96e89e06c8e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,282 | INFO | Classification pool progress: 40/113 chunks completed.
2026-04-14 11:56:33,299 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,301 | WARNING | Classification failed for chunk 8427f829e79567fe83df55ef6ece15e5cda1d680: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  36%|███▋      | 41/113 [00:03<00:05, 14.10it/s]2026-04-14 11:56:33,390 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,390 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,393 | WARNING | Classification failed for chunk be05c1ea6845471bec1ba6bbf22dec7c9a813986: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,396 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,421 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,422 | WARNING | Classification failed for chunk 5e29f957481abbb906b505b16f8cdfd999513b52: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  39%|███▉      | 44/113 [00:03<00:04, 16.48it/s]2026-04-14 11:56:33,495 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,505 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,507 | WARNING | Classification failed for chunk 448d8d53d250469127cefa3e0af58c3709b3f49a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,611 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,611 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,613 | WARNING | Classification failed for chunk e411593a1aa85e7342563927e6b40dafe9ef26f9: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,614 | WARNING | Classification failed for chunk ede436f7817d52a8a885a38666e242c1d509e10a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  42%|████▏     | 47/113 [00:04<00:04, 16.14it/s]2026-04-14 11:56:33,668 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,682 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,683 | WARNING | Classification failed for chunk 572ffe7d274dbacdc29e1866b5054f08b1a77abb: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:33,782 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,790 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:33,815 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Running pipeline for: Qualcom

Extracting pages: Qualcom: 100%|██████████| 1/1 [00:00<00:00,  2.00it/s]
Chunking clean pages: 100%|██████████| 147/147 [00:00<00:00, 2608.00it/s]
Batches: 100%|██████████| 14/14 [00:01<00:00,  8.15it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 183.02it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 178.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 170.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 175.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 155.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 183.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 153.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.62it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 200.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 182.27it/s]<00:00, 80.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 178.57it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 188.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 166.69it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 177.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 182.65it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 169.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 162.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.30it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 153.84it/s]0<00:00, 80.72it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 175.87it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 172.32it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.71it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 80.60it/s]
2026-04-14 11:56:52,538 | INFO | Starting classification pool for 126 retrieved chunks with up to 40 worker threads.
2026-04-14 11:56:52,550 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:56:52,553 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:56:52,553 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:56:52,554 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:56:52,556 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:56:52,556 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:56:52,558 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:56:52,559 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:56:52,560 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:56:52,563 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:56:52,563 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:56:52,563 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:56:52,564 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:56:52,568 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:56:52,568 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:56:52,571 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:56:52,572 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:56:52,573 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:56:52,575 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:56:52,575 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:56:52,577 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:56:52,577 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:56:52,579 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:56:52,580 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:56:52,582 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:56:52,583 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:56:52,583 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:56:52,584 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:56:52,585 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:56:52,586 | INFO | Initialized OpenAI client in worker thread classifier_34
2026-04-14 11:56:52,587 | INFO | Submitted 126 classification tasks to the worker pool.
2026-04-14 11:56:52,589 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:56:52,590 | INFO | Initialized OpenAI client in worker thread classifier_36
Classifying retrieved chunks (40 workers):   0%|          | 0/126 [00:00<?, ?it/s]2026-04-14 11:56:52,592 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:56:52,593 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:56:52,594 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:56:53,709 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/126 [00:01<02:10,  1.04s/it]2026-04-14 11:56:53,720 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,799 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,843 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   2%|▏         | 3/126 [00:01<00:39,  3.14it/s]2026-04-14 11:56:53,870 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,894 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,911 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,911 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:53,919 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,060 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,060 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,061 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   5%|▍         | 6/126 [00:01<00:20,  5.95it/s]2026-04-14 11:56:54,061 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,062 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,063 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,069 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,074 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,078 | INFO | Classification pool progress: 10/126 chunks completed.
2026-04-14 11:56:54,103 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,111 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,188 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  11%|█         | 14/126 [00:01<00:06, 16.29it/s]2026-04-14 11:56:54,355 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,364 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,446 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,625 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,636 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  14%|█▍        | 18/126 [00:01<00:08, 12.77it/s]2026-04-14 11:56:54,696 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,700 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,701 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,707 | INFO | Classification pool progress: 20/126 chunks completed.
2026-04-14 11:56:54,733 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,765 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  17%|█▋        | 22/126 [00:02<00:06, 15.78it/s]2026-04-14 11:56:54,797 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,823 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,824 | WARNING | Classification failed for chunk 51f87275a55130b9b8f8e2f3d108b4a475dea31e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:54,825 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,842 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,857 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,858 | WARNING | Classification failed for chunk 40c0d82ac8464adfd8874a5d5959512e010db342: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:54,996 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:54,997 | WARNING | Classification failed for chunk 5fb3371d4a29c5500cd3b96b3827e470ae3928f0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  21%|██        | 26/126 [00:02<00:06, 16.24it/s]2026-04-14 11:56:55,007 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,106 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,108 | WARNING | Classification failed for chunk 46755030cfc51ee74b9d11c091c6e91042d79f29: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:55,123 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,167 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  23%|██▎       | 29/126 [00:02<00:05, 16.55it/s]2026-04-14 11:56:55,172 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,172 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,177 | INFO | Classification pool progress: 30/126 chunks completed.
2026-04-14 11:56:55,193 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,216 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,248 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,252 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,269 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,287 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,289 | WARNING | Classification failed for chunk 12cd6b859b420d54f4f233c2fbee488b011dab71: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  27%|██▋       | 34/126 [00:02<00:04, 21.38it/s]2026-04-14 11:56:55,294 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,295 | WARNING | Classification failed for chunk 0f5e88e41fd509384cb8e043e3990cdc80c80438: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:55,319 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,374 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,424 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,468 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,470 | WARNING | Classification failed for chunk b6fb180e1aaf6e99516893739113ec7aa209617f: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:55,524 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,641 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,667 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,669 | WARNING | Classification failed for chunk 54d66b12d6f3791768228effd62bf70bbe3faae7: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  29%|██▉       | 37/126 [00:02<00:05, 15.09it/s]2026-04-14 11:56:55,718 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,786 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,817 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,837 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:55,839 | WARNING | Classification failed for chunk 2038d7e87ee73639eb711da7aed53c4951df6591: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:55,840 | INFO | Classification pool progress: 40/126 chunks completed.
Classifying retrieved chunks (40 workers):  32%|███▏      | 40/126 [00:03<00:05, 15.67it/s]2026-04-14 11:56:55,942 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,157 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,157 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,158 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,158 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,159 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,163 | WARNING | Classification failed for chunk edecf3b2abefc58b6868eeaad4c06520c1674a25: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  34%|███▍      | 43/126 [00:03<00:06, 13.11it/s]2026-04-14 11:56:56,172 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,174 | WARNING | Classification failed for chunk bdcd477f2e3a3c061addddef89ebe5b188a995aa: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:56,201 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,211 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,272 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,275 | WARNING | Classification failed for chunk 04c8ed1215067fad51d3961def000fa6d04cd155: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  37%|███▋      | 47/126 [00:03<00:04, 16.87it/s]2026-04-14 11:56:56,284 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,286 | WARNING | Classification failed for chunk e31d50316ee13206d5dd93029408f10db00a9ffd: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:56,300 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,353 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,447 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,449 | WARNING | Classification failed for chunk 9378de7097ea3780ebd9d17474163c2e77a38a40: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:56,451 | INFO | Classification pool progress: 50/126 chunks completed.
Classifying retrieved chunks (40 workers):  40%|███▉      | 50/126 [00:03<00:04, 16.91it/s]2026-04-14 11:56:56,680 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,680 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,683 | WARNING | Classification failed for chunk 24618890152338ab75828ce17692a7e7441cbae8: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:56,684 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,685 | WARNING | Classification failed for chunk 34483b8cdbe659340111ef09745d3a66f8e55140: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:56:56,689 | WARNING | Classification failed for chunk 0c9aee61ccf12c47c3ae7a2a14aa9a87ab94b39d: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  42%|████▏     | 53/126 [00:04<00:04, 15.42it/s]2026-04-14 11:56:56,745 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,966 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:56,993 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:57,005 | WARNING | Classification failed for chunk 42bfd2f5d826266fe633fc5ea8ddaece67882557: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  44%|████▎     | 55/126 [00:04<00:06, 11.82it/s]2026-04-14 11:56:57,082 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:57,094 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:56:57,215 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Running pipeline for: Samsung

Extracting pages: Samsung: 100%|██████████| 1/1 [00:00<00:00,  1.49it/s]
Chunking clean pages: 100%|██████████| 267/267 [00:00<00:00, 3720.63it/s]
Batches: 100%|██████████| 14/14 [00:02<00:00,  6.98it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 47.88it/s]0<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 42.71it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 184.58it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 155.03it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.22it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.37it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 177.72it/s]<00:00, 52.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 167.53it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 188.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 173.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 205.21it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 168.39it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 187.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 51.67it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 171.67it/s]0<00:00, 63.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 178.09it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 162.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 171.64it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 63.01it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 160.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.91it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 50.81it/s]00<00:00, 66.18it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.12it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 62.80it/s]
2026-04-14 11:57:38,140 | INFO | Starting classification pool for 93 retrieved chunks with up to 40 worker threads.
2026-04-14 11:57:38,150 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:57:38,150 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:57:38,151 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:57:38,151 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:57:38,152 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:57:38,152 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:57:38,156 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:57:38,156 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:57:38,156 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:57:38,156 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:57:38,157 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:57:38,158 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:57:38,162 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:57:38,164 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:57:38,164 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:57:38,166 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:57:38,166 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:57:38,169 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:57:38,169 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:57:38,170 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:57:38,172 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:57:38,172 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:57:38,173 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:57:38,177 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:57:38,179 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:57:38,184 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:57:38,185 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:57:38,186 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:57:38,186 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:57:38,189 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:57:38,190 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:57:38,190 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:57:38,191 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:57:38,192 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:57:38,193 | INFO | Submitted 93 classification tasks to the worker pool.
2026-04-14 11:57:38,193 | INFO | Initialized OpenAI client in worker thread classifier_34
Classifying retrieved chunks (40 workers):   0%|          | 0/93 [00:00<?, ?it/s]2026-04-14 11:57:38,195 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:57:38,195 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:57:38,197 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:57:38,200 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:57:38,204 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:57:39,241 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,242 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,242 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,285 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/93 [00:01<01:38,  1.07s/it]2026-04-14 11:57:39,315 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,366 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,369 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,395 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   2%|▏         | 2/93 [00:01<00:45,  1.99it/s]2026-04-14 11:57:39,400 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,456 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,462 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,473 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,483 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,483 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,508 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,531 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   9%|▊         | 8/93 [00:01<00:08,  9.78it/s]2026-04-14 11:57:39,674 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,675 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,676 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,676 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,750 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,754 | INFO | Classification pool progress: 10/93 chunks completed.
2026-04-14 11:57:39,803 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  12%|█▏        | 11/93 [00:01<00:08, 10.18it/s]2026-04-14 11:57:39,988 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:39,991 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  14%|█▍        | 13/93 [00:01<00:07, 10.34it/s]2026-04-14 11:57:40,036 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,053 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,054 | WARNING | Classification failed for chunk bd885713e11129c534891651490804c19570a681: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,196 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,197 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,198 | WARNING | Classification failed for chunk 56f671a707e1cb6e70ce24f14b3084484e4ebfb0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  17%|█▋        | 16/93 [00:01<00:06, 11.49it/s]2026-04-14 11:57:40,202 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,204 | WARNING | Classification failed for chunk 6645980d011f67560b0a0e998c85d98819515ae3: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,238 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,266 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,324 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,326 | WARNING | Classification failed for chunk 8dc2871497d25f1b5e1d061ece08c63a05f2bcd2: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,326 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  20%|██        | 19/93 [00:02<00:05, 13.94it/s]2026-04-14 11:57:40,329 | WARNING | Classification failed for chunk 63b5d4fd06004b53c15e6c633f8cb06ffb6b22eb: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,331 | INFO | Classification pool progress: 20/93 chunks completed.
2026-04-14 11:57:40,424 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,427 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,428 | WARNING | Classification failed for chunk 2c401fd7e86c222596dfa13521e412b4c60c675a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  23%|██▎       | 21/93 [00:02<00:04, 15.01it/s]2026-04-14 11:57:40,503 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,507 | WARNING | Classification failed for chunk d4e6e99fc6f5f4d14a42521ab73fa455c331d99b: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,532 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  25%|██▍       | 23/93 [00:02<00:04, 15.78it/s]2026-04-14 11:57:40,552 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,578 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,745 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,761 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  27%|██▋       | 25/93 [00:02<00:05, 13.00it/s]2026-04-14 11:57:40,766 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,767 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,768 | WARNING | Classification failed for chunk 44a440ade9e5dbc7c325185383fb065b16e8f90a: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:40,771 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,868 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,868 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,870 | WARNING | Classification failed for chunk 5d55b3c7a5fb38d0b2f88013923fcd433c2e4029: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  29%|██▉       | 27/93 [00:02<00:04, 14.19it/s]2026-04-14 11:57:40,875 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,889 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,890 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,918 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:40,921 | INFO | Classification pool progress: 30/93 chunks completed.
2026-04-14 11:57:40,984 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,057 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  33%|███▎      | 31/93 [00:02<00:03, 16.65it/s]2026-04-14 11:57:41,088 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,110 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,262 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,267 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,272 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,283 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,311 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  37%|███▋      | 34/93 [00:03<00:04, 14.70it/s]2026-04-14 11:57:41,330 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,371 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,373 | WARNING | Classification failed for chunk 731905d8ece8f47c96858f434562419fffe40cf4: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,413 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  40%|███▉      | 37/93 [00:03<00:03, 17.45it/s]2026-04-14 11:57:41,435 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,480 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,481 | WARNING | Classification failed for chunk 1592cb7393ef4bdd38f26dd0270240c1120d17f0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,557 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,560 | INFO | Classification pool progress: 40/93 chunks completed.
Classifying retrieved chunks (40 workers):  43%|████▎     | 40/93 [00:03<00:02, 18.35it/s]2026-04-14 11:57:41,570 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,768 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,771 | WARNING | Classification failed for chunk 3e060ef63625c71e4e48599a8d1a023c2a4f5677: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,773 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,774 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,777 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,778 | WARNING | Classification failed for chunk 149a6fe92d5239054d950da7c847d353ad5f0656: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  46%|████▌     | 43/93 [00:03<00:03, 16.54it/s]2026-04-14 11:57:41,788 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,790 | WARNING | Classification failed for chunk d84889c901ce2d9ffcacbbb199a573c46e207607: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,795 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,797 | WARNING | Classification failed for chunk fbcf6a4bbbd49d5286681eacb08bdd78b9e110a5: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,818 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,825 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,845 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,846 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:41,848 | WARNING | Classification failed for chunk 1ca8b69e288c03f081d03c23d31d52eebdb3a1e9: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:41,915 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  52%|█████▏    | 48/93 [00:03<00:02, 21.55it/s]2026-04-14 11:57:42,024 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:42,026 | WARNING | Classification failed for chunk d4eac94067ea7fd4131532820a47fba76c041407: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:42,034 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:42,035 | WARNING | Classification failed for chunk b8b23e155d28d2d7bcbb700239d864d052a2ee4e: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:42,037 | INFO | Classification pool progress: 50/93 chunks completed.
2026-04-14 11:57:42,294 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:42,294 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:42,295 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  55%|█████▍    | 51/93 [00:04<00:02, 14.75it/s]2026-04-14 11:57:42,297 | WARNING | Classification failed for chunk 51cefd9b506b76f14d56c6c608b53529158a4ab6: Classification failed after 2 attempts: 'secondary_category' must be a string or null.

Running pipeline for: TSMC

Extracting pages: TSMC: 100%|██████████| 1/1 [00:01<00:00,  1.46s/it]
Chunking clean pages: 100%|██████████| 255/255 [00:00<00:00, 2409.91it/s]
Batches: 100%|██████████| 19/19 [00:02<00:00,  9.27it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.22it/s]<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 200.92it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 198.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.04it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 182.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 168.29it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 204.88it/s]<00:00, 78.14it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 202.80it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 205.94it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 207.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 202.47it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.77it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 193.35it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 210.49it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 202.25it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 199.76it/s]0<00:00, 82.83it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.54it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 189.36it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 192.38it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.23it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 205.50it/s]
Running retrieval queries: 100%|██████████| 23/23 [00:00<00:00, 82.17it/s]
2026-04-14 11:57:50,344 | INFO | Starting classification pool for 147 retrieved chunks with up to 40 worker threads.
2026-04-14 11:57:50,352 | INFO | Initialized OpenAI client in worker thread classifier_2
2026-04-14 11:57:50,353 | INFO | Initialized OpenAI client in worker thread classifier_5
2026-04-14 11:57:50,353 | INFO | Initialized OpenAI client in worker thread classifier_0
2026-04-14 11:57:50,354 | INFO | Initialized OpenAI client in worker thread classifier_7
2026-04-14 11:57:50,354 | INFO | Initialized OpenAI client in worker thread classifier_3
2026-04-14 11:57:50,354 | INFO | Initialized OpenAI client in worker thread classifier_8
2026-04-14 11:57:50,354 | INFO | Initialized OpenAI client in worker thread classifier_1
2026-04-14 11:57:50,354 | INFO | Initialized OpenAI client in worker thread classifier_4
2026-04-14 11:57:50,356 | INFO | Initialized OpenAI client in worker thread classifier_6
2026-04-14 11:57:50,361 | INFO | Initialized OpenAI client in worker thread classifier_11
2026-04-14 11:57:50,361 | INFO | Initialized OpenAI client in worker thread classifier_9
2026-04-14 11:57:50,361 | INFO | Initialized OpenAI client in worker thread classifier_10
2026-04-14 11:57:50,362 | INFO | Initialized OpenAI client in worker thread classifier_12
2026-04-14 11:57:50,363 | INFO | Initialized OpenAI client in worker thread classifier_13
2026-04-14 11:57:50,363 | INFO | Initialized OpenAI client in worker thread classifier_15
2026-04-14 11:57:50,364 | INFO | Initialized OpenAI client in worker thread classifier_14
2026-04-14 11:57:50,367 | INFO | Initialized OpenAI client in worker thread classifier_16
2026-04-14 11:57:50,367 | INFO | Initialized OpenAI client in worker thread classifier_17
2026-04-14 11:57:50,369 | INFO | Initialized OpenAI client in worker thread classifier_18
2026-04-14 11:57:50,369 | INFO | Initialized OpenAI client in worker thread classifier_19
2026-04-14 11:57:50,371 | INFO | Initialized OpenAI client in worker thread classifier_21
2026-04-14 11:57:50,371 | INFO | Initialized OpenAI client in worker thread classifier_20
2026-04-14 11:57:50,371 | INFO | Initialized OpenAI client in worker thread classifier_22
2026-04-14 11:57:50,373 | INFO | Initialized OpenAI client in worker thread classifier_23
2026-04-14 11:57:50,374 | INFO | Initialized OpenAI client in worker thread classifier_24
2026-04-14 11:57:50,375 | INFO | Initialized OpenAI client in worker thread classifier_26
2026-04-14 11:57:50,377 | INFO | Initialized OpenAI client in worker thread classifier_27
2026-04-14 11:57:50,377 | INFO | Initialized OpenAI client in worker thread classifier_25
2026-04-14 11:57:50,377 | INFO | Initialized OpenAI client in worker thread classifier_28
2026-04-14 11:57:50,378 | INFO | Initialized OpenAI client in worker thread classifier_30
2026-04-14 11:57:50,379 | INFO | Initialized OpenAI client in worker thread classifier_31
2026-04-14 11:57:50,380 | INFO | Initialized OpenAI client in worker thread classifier_29
2026-04-14 11:57:50,380 | INFO | Initialized OpenAI client in worker thread classifier_32
2026-04-14 11:57:50,382 | INFO | Submitted 147 classification tasks to the worker pool.
2026-04-14 11:57:50,382 | INFO | Initialized OpenAI client in worker thread classifier_33
2026-04-14 11:57:50,384 | INFO | Initialized OpenAI client in worker thread classifier_34
Classifying retrieved chunks (40 workers):   0%|          | 0/147 [00:00<?, ?it/s]2026-04-14 11:57:50,384 | INFO | Initialized OpenAI client in worker thread classifier_35
2026-04-14 11:57:50,385 | INFO | Initialized OpenAI client in worker thread classifier_36
2026-04-14 11:57:50,385 | INFO | Initialized OpenAI client in worker thread classifier_37
2026-04-14 11:57:50,387 | INFO | Initialized OpenAI client in worker thread classifier_38
2026-04-14 11:57:50,389 | INFO | Initialized OpenAI client in worker thread classifier_39
2026-04-14 11:57:51,474 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   1%|          | 1/147 [00:01<02:36,  1.08s/it]2026-04-14 11:57:51,527 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,542 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,547 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,551 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,609 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,733 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,734 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,735 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   4%|▍         | 6/147 [00:01<00:25,  5.62it/s]2026-04-14 11:57:51,737 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,752 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,784 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:51,787 | INFO | Classification pool progress: 10/147 chunks completed.
2026-04-14 11:57:51,790 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,023 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):   8%|▊         | 12/147 [00:01<00:13, 10.04it/s]2026-04-14 11:57:52,042 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,043 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,050 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,111 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,254 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  10%|█         | 15/147 [00:01<00:12, 10.76it/s]2026-04-14 11:57:52,358 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,436 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,484 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,493 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  12%|█▏        | 17/147 [00:02<00:12, 10.14it/s]2026-04-14 11:57:52,534 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,540 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,605 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,606 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,613 | WARNING | Classification failed for chunk 131b8a714f7be53036b8c87760eff838b0248fab: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  13%|█▎        | 19/147 [00:02<00:11, 11.20it/s]2026-04-14 11:57:52,685 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,787 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,792 | INFO | Classification pool progress: 20/147 chunks completed.
2026-04-14 11:57:52,852 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,889 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,889 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:52,893 | WARNING | Classification failed for chunk 526a71b0a1c56d42540e90540faa1d59ca280d14: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:52,897 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  14%|█▍        | 21/147 [00:02<00:12,  9.77it/s]2026-04-14 11:57:53,027 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,027 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,044 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  16%|█▌        | 23/147 [00:02<00:11, 10.50it/s]2026-04-14 11:57:53,070 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,074 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,112 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,175 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  17%|█▋        | 25/147 [00:02<00:10, 11.53it/s]2026-04-14 11:57:53,181 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,302 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,302 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  18%|█▊        | 27/147 [00:02<00:09, 12.46it/s]2026-04-14 11:57:53,430 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,432 | WARNING | Classification failed for chunk d1c4b4135b8444283772bde6c9a24e6f66d78dba: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:53,458 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,495 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,497 | WARNING | Classification failed for chunk 112014d38928b3e105eefc5e896c9b439aa19bb8: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  20%|█▉        | 29/147 [00:03<00:10, 11.78it/s]2026-04-14 11:57:53,502 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,503 | WARNING | Classification failed for chunk f9e4fcdb58df295b6736fd1f9f5ea397f7e3219c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:53,504 | INFO | Classification pool progress: 30/147 chunks completed.
2026-04-14 11:57:53,523 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,525 | WARNING | Classification failed for chunk 4d5fe470abdf4abb1965fae86c2544489b0ecbad: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:53,592 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,597 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  22%|██▏       | 33/147 [00:03<00:06, 17.25it/s]2026-04-14 11:57:53,697 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,828 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,878 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,884 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,885 | WARNING | Classification failed for chunk d5896344c0f5329a147a123d8326e25b820ead5c: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  24%|██▍       | 36/147 [00:03<00:07, 14.23it/s]2026-04-14 11:57:53,908 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,908 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,910 | WARNING | Classification failed for chunk dc74795fe0352b750cce34a9cadbabba13e3c0d0: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:53,942 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,943 | WARNING | Classification failed for chunk c7b6dad4ab3d293e43fe3759e8bce46fdda02fd8: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:53,946 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:53,948 | INFO | Classification pool progress: 40/147 chunks completed.
2026-04-14 11:57:53,970 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,026 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,028 | WARNING | Classification failed for chunk ecc90c5ccb9deb489fc2bcb3676d1f1bea7cc28b: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  29%|██▊       | 42/147 [00:03<00:05, 20.90it/s]2026-04-14 11:57:54,128 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,132 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,134 | WARNING | Classification failed for chunk 49ed9f909f8c03b46be39ad3d669069fb01d9aad: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:54,203 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,206 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,213 | WARNING | Classification failed for chunk 8f35b9eb5e381697fcba5651ea0ef0ead6625eb1: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:54,216 | WARNING | Classification failed for chunk fae80f94ef3fe26195f74d54ec457fcfcf8f6921: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  31%|███       | 45/147 [00:03<00:05, 19.33it/s]2026-04-14 11:57:54,351 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,351 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,351 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,352 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,355 | WARNING | Classification failed for chunk f0b1fe223e0023fd6f9184b2f21a58d6c0c72354: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
Classifying retrieved chunks (40 workers):  33%|███▎      | 48/147 [00:03<00:04, 19.86it/s]2026-04-14 11:57:54,381 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,383 | INFO | Classification pool progress: 50/147 chunks completed.
2026-04-14 11:57:54,385 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,392 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,429 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,488 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,529 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  36%|███▌      | 53/147 [00:04<00:04, 22.55it/s]2026-04-14 11:57:54,546 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,546 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,593 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,621 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,623 | WARNING | Classification failed for chunk 4c8a2fbe264e09f429d1f396e464e43d75f4a8c1: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:54,875 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:54,875 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
Classifying retrieved chunks (40 workers):  39%|███▉      | 57/147 [00:04<00:05, 17.45it/s]2026-04-14 11:57:54,939 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:55,016 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:55,018 | WARNING | Classification failed for chunk f804e2f11ca830ef56fabfd18596ffbd78ba9f7d: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:55,085 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-04-14 11:57:55,087 | WARNING | Classification failed for chunk e15c282d744db5f17fc1651a4d465ac72049df63: Classification failed after 2 attempts: 'secondary_category' must be a string or null.
2026-04-14 11:57:55,089 | INFO | Classification pool progress: 60/147 chunks completed.
Classifying retrieved chunks (40 workers):  41%|████      | 60/147 [00:04<00:05, 16.51it/s]2026-04-14 11:57:55,103 | INFO | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

Completed pipeline runs for 10 company/corpus groups.

## 14. Export Combined QA Outputs

The primary deliverables are the company-specific Excel workbooks.
This section also writes optional combined QA outputs so you can inspect the full corpus after
the company-level runs have finished.

In [32]:
company_summary_df = pd.concat(
    [result["company_summary_df"] for result in company_results],
    ignore_index=True,
) if company_results else pd.DataFrame()

combined_final_df = pd.concat(
    [result["final_df"] for result in company_results if not result["final_df"].empty],
    ignore_index=True,
) if company_results else pd.DataFrame()

combined_summary_path = CONFIG["combined_export_folder"] / "company_summary.csv"
company_summary_df.to_csv(combined_summary_path, index=False)

if CONFIG["export_combined_master"] and not combined_final_df.empty:
    combined_master_excel_path = CONFIG["combined_export_folder"] / "combined_master.xlsx"
    combined_master_pickle_path = CONFIG["combined_export_folder"] / "combined_master.pkl"
    sanitize_dataframe_for_excel(combined_final_df).to_excel(combined_master_excel_path, index=False, engine="openpyxl")
    save_pickle(combined_final_df, combined_master_pickle_path)
    print(f"Combined master export written to: {combined_master_excel_path.resolve()}")

print(f"Company summary written to: {combined_summary_path.resolve()}")
display(company_summary_df)

Combined master export written to: /Users/paulkoslowsky/Github/Jakop/outputs/final_pipeline/combined/combined_master.xlsx
Company summary written to: /Users/paulkoslowsky/Github/Jakop/outputs/final_pipeline/combined/company_summary.csv

,firm_name,files_processed,pages_total,pages_excluded,chunks_total,chunks_indexed,retrieved_rows,deduplicated_retrieval_rows,classification_rows,final_relevant_rows,low_output_warning
0,ASML,1,210,23,477,474,575,131,131,73,False
1,Elmos,1,64,0,192,191,575,88,88,26,True
2,Infineon,1,194,2,452,450,575,123,123,64,False
3,Intel,1,185,13,386,385,575,125,125,43,True
4,MediaTek,1,311,26,480,472,575,77,77,28,True
5,Micron,1,119,0,297,297,575,92,92,42,True
6,NXP,1,143,1,425,423,575,113,113,43,True
7,Qualcom,1,148,1,420,419,575,126,126,41,True
8,Samsung,1,271,4,454,428,575,93,93,35,True
9,TSMC,1,276,21,620,594,575,147,147,65,False

## 15. Quality Checks

This section gives the final QA overview requested for the thesis workflow.
It reports:

- files processed
- page exclusions
- chunk counts
- retrieval counts
- final relevant rows
- counts by company
- counts by year
- counts by normalized `strategy_category`

This section is especially useful after a `single_company` test run.

In [33]:
if not company_summary_df.empty:
    print("Company-level QA summary")
    print("------------------------")
    display(company_summary_df)

if not combined_final_df.empty:
    print("\nFinal rows by company")
    display(safe_value_counts(combined_final_df, "firm_name").rename("count").to_frame())

    print("\nFinal rows by year")
    display(safe_value_counts(combined_final_df, "fiscal_year").rename("count").to_frame())

    print("\nFinal rows by strategy_category")
    display(safe_value_counts(combined_final_df, "strategy_category").rename("count").to_frame())

    print("\nRetrieval counts by company")
    retrieval_counts_df = pd.DataFrame(
        [
            {
                "firm_name": result["company_name"],
                "retrieved_rows": len(result["retrieval_df"]),
                "deduplicated_rows": len(result["deduplicated_retrieval_df"]),
            }
            for result in company_results
        ]
    )
    display(retrieval_counts_df)

Company-level QA summary
------------------------

,firm_name,files_processed,pages_total,pages_excluded,chunks_total,chunks_indexed,retrieved_rows,deduplicated_retrieval_rows,classification_rows,final_relevant_rows,low_output_warning
0,ASML,1,210,23,477,474,575,131,131,73,False
1,Elmos,1,64,0,192,191,575,88,88,26,True
2,Infineon,1,194,2,452,450,575,123,123,64,False
3,Intel,1,185,13,386,385,575,125,125,43,True
4,MediaTek,1,311,26,480,472,575,77,77,28,True
5,Micron,1,119,0,297,297,575,92,92,42,True
6,NXP,1,143,1,425,423,575,113,113,43,True
7,Qualcom,1,148,1,420,419,575,126,126,41,True
8,Samsung,1,271,4,454,428,575,93,93,35,True
9,TSMC,1,276,21,620,594,575,147,147,65,False

Final rows by company

           count
firm_name
ASML          73
TSMC          65
Infineon      64
Intel         43
NXP           43
Micron        42
Qualcom       41
Samsung       35
MediaTek      28
Elmos         26

Final rows by year

             count
fiscal_year
2017           460

Final rows by strategy_category

                                  count
strategy_category
E6 Partner Network Strengthening    119
E2 Footprint Diversification         91
E7 SCRM and Visibility               68
E5 Product Standardisation           65
E1 Operational Buffers               41
E3 Supply Option Diversification     39
I-ExportControlCompliance            14
E4 Robust Distribution               13
I-GovernmentSubsidy                   9
I-exposureconcentration               1

Retrieval counts by company

  firm_name  retrieved_rows  deduplicated_rows
0      ASML             575                131
1     Elmos             575                 88
2  Infineon             575                123
3     Intel             575                125
4  MediaTek             575                 77
5    Micron             575                 92
6       NXP             575                113
7   Qualcom             575                126
8   Samsung             575                 93
9      TSMC             575                147

## 16. One-Company Test Views

This section is designed for the `single_company` workflow.
It surfaces the company-specific diagnostics that are most useful when refining the pipeline:

- page-level exclusions
- chunk-level QA
- retrieval counts by theme/query
- final label counts
- a few sample rows for manual inspection

In [35]:
if CONFIG["run_mode"] == "single_company" and company_results:
    single_result = company_results[0]

    print("Page summary")
    display(single_result["page_summary_df"])

    print("\nChunk summary")
    display(single_result["chunk_summary_df"])

    if not single_result["retrieval_df"].empty:
        print("\nRetrieval counts by theme")
        display(
            single_result["retrieval_df"]
            .groupby("retrieval_theme")
            .size()
            .rename("count")
            .reset_index()
            .sort_values("count", ascending=False)
        )

        print("\nRetrieval counts by query")
        display(
            single_result["retrieval_df"]
            .groupby("retrieval_query")
            .size()
            .rename("count")
            .reset_index()
            .sort_values("count", ascending=False)
        )

    if not single_result["final_df"].empty:
        print("\nFinal normalized strategy-category counts")
        display(
            single_result["final_df"]["strategy_category"]
            .value_counts(dropna=False)
            .rename("count")
            .to_frame()
        )

        print("\nSample final rows")
        sample_columns = [
            "firm_name",
            "fiscal_year",
            "page_number",
            "section",
            "retrieval_query",
            "strategy_category",
            "secondary_category",
            "main_point",
            "confidence",
            "passage",
        ]
        display(single_result["final_df"][sample_columns].head(10))

## 17. Manual Inspection Helpers

These optional views are useful when you want to inspect likely problem areas manually.
For example:

- pages excluded as table-of-contents or low-information
- chunks excluded before indexing
- raw classification drift before normalization

These checks are especially useful when testing one company before running the full corpus.

In [36]:
if company_results:
    first_result = company_results[0]

    if not first_result["pages_df"].empty:
        print("Excluded pages preview")
        excluded_pages_preview = first_result["pages_df"].loc[
            first_result["pages_df"]["is_excluded"],
            ["firm_name", "fiscal_year", "page_number", "exclusion_reason", "section", "page_text_raw"],
        ].head(10)
        display(excluded_pages_preview)

    if not first_result["chunks_df"].empty:
        print("\nExcluded chunks preview")
        excluded_chunks_preview = first_result["chunks_df"].loc[
            first_result["chunks_df"]["is_excluded"],
            ["firm_name", "fiscal_year", "page_number", "exclusion_reason", "passage"],
        ].head(10)
        display(excluded_chunks_preview)

    if (
        CONFIG["run_classification"]
        and not first_result["classified_df"].empty
        and "strategy_category_raw" in first_result["classified_df"].columns
    ):
        print("\nRaw-to-normalized strategy label preview")
        preview_columns = [
            "firm_name",
            "fiscal_year",
            "retrieval_theme",
            "strategy_category_raw",
            "strategy_category",
            "secondary_category",
        ]
        display(first_result["classified_df"][preview_columns].head(15))

Excluded pages preview

   firm_name  fiscal_year  page_number      exclusion_reason section                   page_text_raw
0       ASML         2017            1  empty_after_cleaning     NaN
1       ASML         2017            2  empty_after_cleaning     NaN
3       ASML         2017            4  empty_after_cleaning     NaN     ASML INTEGRATED REPORT 2017
8       ASML         2017            9  empty_after_cleaning     NaN
9       ASML         2017           10  empty_after_cleaning     NaN  ASML INTEGRATED REPORT 2017\n3
22      ASML         2017           23  empty_after_cleaning     NaN
29      ASML         2017           30  empty_after_cleaning     NaN
37      ASML         2017           38  empty_after_cleaning     NaN
43      ASML         2017           44  empty_after_cleaning     NaN
47      ASML         2017           48  empty_after_cleaning     NaN

Excluded chunks preview

,firm_name,fiscal_year,page_number,exclusion_reason,passage
235,ASML,2017,101,low_alpha_ratio,"Fair value differences 3\n—\n—\n27.9\n—\n—\n—\n27.9\nPurchase of treasury shares\n(4.8)\n—\n—\n(400.0)\n—\n—\n(400.0)\nCancellation of treasury shares\n—\n—\n—\n—\n—\n—\n—\n18,..."
394,ASML,2017,167,low_alpha_ratio,"Total direct compensation, pension and other benefits\nThe remuneration of key management personnel, comprising of members of the BoM in 2017, 2016 and 2015 was as follows:\nFi..."
398,ASML,2017,168,low_alpha_ratio,"Nickl\n1/20/2017\nConditional\nNo\n11,629\n114.05\n1/20/2020\n—\n1/20/2022\n1/22/2016\nConditional\nNo\n11,205\n83.60\n1/22/2019\n—\n1/22/2021\n1/23/2015\nConditional\nNo\n10,7..."

Raw-to-normalized strategy label preview

,firm_name,fiscal_year,retrieval_theme,strategy_category_raw,strategy_category,secondary_category
0,ASML,2017,E7 SCRM and Visibility,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
1,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
2,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
3,ASML,2017,E3 Supply Option Diversification,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E3 Supply Option Diversification
4,ASML,2017,E7 SCRM and Visibility,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
5,ASML,2017,E3 Supply Option Diversification,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
6,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,0
7,ASML,2017,E6 Partner Network Strengthening,NaN,NaN,NaN
8,ASML,2017,E3 Supply Option Diversification,E3 Supply Option Diversification,E3 Supply Option Diversification,0
9,ASML,2017,E1 Operational Buffers,E1 Operational Buffers,E1 Operational Buffers,0
10,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
11,ASML,2017,E7 SCRM and Visibility,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E7 SCRM and Visibility
12,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,0
13,ASML,2017,Broad geopolitical context,E2 Footprint Diversification,E2 Footprint Diversification,0
14,ASML,2017,E6 Partner Network Strengthening,E6 Partner Network Strengthening,E6 Partner Network Strengthening,0

## Notes on Extension

The final notebook is intentionally organized so major parts can be swapped later:

- PDF parser:
  Replace `extract_pdf_pages()` if you want to use `pdfplumber` or OCR.
- Embedding model:
  Change `embedding_model_name` and keep the rest of the pipeline stable.
- Vector store:
  Replace FAISS helpers if you later prefer Chroma or another local index.
- LLM provider:
  Replace `request_openai_json_response()` and keep the validation and normalization logic.

Recommended workflow:

1. Run `single_company` on Intel and inspect the QA views.
2. Test Samsung and MediaTek to confirm the company-specific scope rules.
3. Once the single-company outputs look clean, switch to `full_corpus`.